### ISSUE TITLE
Build Failing: Not able to import icon

### ISSUE THREAD

**Issue by vasa-develop** [blocknative/onboard#160]
I'm adding an icon for Torus(for adding the torus plugin), but somehow the build process fails, throwing the following error:

```
[!] (plugin image) TypeError [ERR_INVALID_ARG_TYPE]: Could not load /home/vasa/Desktop/simpleaswater/dappkit/contributions/onboard/src/modules/select/wallet-icons/icon-torus.png (imported by /home/vasa/Desktop/simpleaswater/dappkit/contributions/onboard/src/modules/select/wallets/torus.ts): The "to" argument must be of type string. Received type undefined
```

Let me know if you need any system details.

**Comment by aaronbarnardsound** [comment]
Hey @vasa-develop what size was the image that you were trying to import? `rollup-plugin-img` has size restrictions as a default which may be throwing the error. I have been trying to keep the logo icons below 20k as they don't need to be very large.

**Comment by vasa-develop** [comment]
Hey @aaronbarnardsound 
Here is the icon I was using
![icon-torus](https://user-images.githubusercontent.com/28847087/72103133-92b4a780-334e-11ea-9574-ed2b4c2e2d89.png)

It doesn't seem that big to me.

**Comment by aaronbarnardsound** [comment]
Yeah it was due to the size being too large for `rollup-plugin-img`. I reduced the size to 4kb and it built fine, so I am going to close this for now.
