### ISSUE TITLE
Adjust wallet urls according to network.

### ISSUE THREAD

**Issue by TomAFrench** [blocknative/onboard#192]
Currently Authereum's url always points at https://authereum.com, ideally this would automatically adjust based on the dapp's network e.g. https://kovan.authereum.com

**Comment by aaronbarnardsound** [comment]
Yeah that's a good point. I think it would just be a matter of using the `networkName` function that is already imported and using a template string to create the `url` based on the `networkId`:

```javascript
{
  // ...other params
  url: `https://${networkId === 1 ? 'accounts' : networkName(networkId)}.authereum.org/`
}
```

I am not sure if any of the other SDK wallets have this same pattern with the link, so I will need to look in to if any of the other wallets need their `url` changed to fit this pattern as well.

Would you be interested in creating a PR for this issue?

**Comment by TomAFrench** [comment]
Sure thing. Your snippet looks like it would definitely do the job. One thing

I've had a look at the other wallets and they don't seem to host different networks on different subdomains etc. so I don't think that we can do something similar for them.
