### ISSUE TITLE
Authereum Build Error (Rollup Apps)

### ISSUE THREAD

**Issue by aaronbarnardsound** [blocknative/onboard#214]
The Authereum SDK currently errors when trying to build in a Rollup app. 

<img width="934" alt="Screen Shot 2020-02-21 at 10 10 14 AM" src="https://user-images.githubusercontent.com/29873495/74990141-8ae03b00-5496-11ea-872a-fe1f215155c6.png">

Commenting the out `instanceof` check from the following section in the module seems to fix it: 
```javascript
if (config instanceof AuthereumSDK_1.default) {
  authereumClient = config;
  config = authereumClient.config;
}
```

It appears that `AuthereumSDK_1.default` is `undefined` and seems to be causing the issue. I have replicated this in a basic rollup build using Authereum directly without Onboard.

@miguelmota Have you guys successfully used Authereum in a Rollup app? If so, is there a specific config parameter or plugin that is necessary?

**Comment by aaronbarnardsound** [comment]
Closing for the moment as it is documented in our docs that Authereum doesn't currently work in Rollup builds

**Comment by miguelmota** [comment]
@aaronbarnardsound sorry I missed the initial comment but will get this resolved now. Can you share the rollup setup you were using?

**Comment by aaronbarnardsound** [comment]
@miguelmota No worries, I have a repo here that you can clone and replicate the issue: https://github.com/aaronbarnardsound/onboard-rollup

It is created from the basic rollup app template with a few plugins to make everything work. Let me know how you go with it and if it is just a matter of changing the rollup config or not. Thanks!

**Comment by miguelmota** [comment]
@aaronbarnardsound thanks for showing me the rollup starter app. I was able to  figure out the issues and get it to build. 

Authereum sdk `version 0.0.4-beta.153` or higher should work now. I [forked](https://github.com/authereum/rollup-starter-app) the rollup starter app and added authereum. You can see the rollup config [diff here](https://github.com/authereum/rollup-starter-app/commit/c08ced515e5f78ea55092719ab0ca0b29630f45e#diff-ff6e5f22a9c7e66987b19c0199636480). To summarize the additional plugins needed are:

- [`@rollup/plugin-json`](https://github.com/rollup/plugins/tree/master/packages/json)
- [`rollup-plugin-node-builtins`](https://github.com/calvinmetcalf/rollup-plugin-node-builtins)
- [`rollup-plugin-node-globals`](https://github.com/calvinmetcalf/rollup-plugin-node-globals)

and this is the plugin order I used:

```js
  plugins: [
    resolve({
      browser: true
    }),
    json(),
    commonjs(),
    globals(),
    builtins()
  ]
```

Let me know if you're seeing issues. Thanks!

**Comment by aaronbarnardsound** [comment]
Hey @miguelmota I am now getting the following error:

![Screen Shot 2020-05-18 at 9 47 31 AM](https://user-images.githubusercontent.com/29873495/82163161-c1d6b900-98ec-11ea-984b-e62a8032a316.png)

![Screen Shot 2020-05-18 at 9 48 12 AM](https://user-images.githubusercontent.com/29873495/82163164-c307e600-98ec-11ea-8805-f4e41b31e195.png)

**Comment by miguelmota** [comment]
@aaronbarnardsound interesting, was this using the same config I used above?

**Comment by aaronbarnardsound** [comment]
@miguelmota Yeah that is using essentially the same config. Instead of `rollup-plugin-node-builtins` and `rollup-plugin-node-globals` I am using [`rollup-plugin-node-polyfills`](https://github.com/ionic-team/rollup-plugin-node-polyfills), which is the same thing but has updated dependencies which is needed to work with Onboard's code-splitting. Try checking out my [example repo](https://github.com/aaronbarnardsound/onboard-rollup) to see the error.

**Comment by miguelmota** [comment]
Hey @aaronbarnardsound, thanks for the example repo; I was to able to reproduce the issue and update the sdk with a patch. Try authereum version 0.0.4-beta.157 or higher and let me know if it works or not.
