### ISSUE TITLE
WalletConnect QR Code cannot be shown again after dismissing

### ISSUE THREAD

**Issue by suhailgme** [blocknative/onboard#241]
The WalletConnect QR code does not appear again after dismissing it. Clicking on the WalletConnect icon the first time successfully shows the QR code. After dismissing it and clicking "Try Again" in the "Login and Authorize your Wallet Modal", only a spinner is shown. If all modals are closed and an attempt to connect to WalletConnect occurs again, only a spinner is shown. See GIF for more details:

![walletConnect](https://user-images.githubusercontent.com/16081825/76272555-5fed3980-6241-11ea-8bd3-861e303126e4.gif)

**Comment by aaronbarnardsound** [comment]
This appears to a bug with WalletConnect. Have created an issue in the repo: https://github.com/WalletConnect/walletconnect-monorepo/issues/243

**Comment by taylorjdawson** [comment]
Bug still not fixed, have re-raised the issue; see [comment](https://github.com/WalletConnect/walletconnect-monorepo/issues/243#issuecomment-850439821).

**Comment by taylorjdawson** [comment]
This is a WallletConnect issue, waiting for them to resolve see comment above 👆🏾
