### ISSUE TITLE
Coinbase not working at all 

### ISSUE THREAD

**Issue by jeffscottward** [blocknative/onboard#308]
Upon adding `{ walletName: "coinbase", preferred: true }` per the setup docs, no Coinbase item shows up.
![Screen Shot 2020-04-16 at 6 36 48 PM](https://user-images.githubusercontent.com/1263486/79513209-4219ae00-8011-11ea-95e1-4c293d67a4cf.png)

**Comment by cmeisl** [comment]
@jeffscottward Is your Onboard screen capture on desktop? Coinbase is only supported on mobile platforms.

**Comment by cmeisl** [comment]
@jeffscottward for clarity, we do have a walletlink branch here to support using Coinbase SDK to use their mobile wallet on desktop, similar to walletconnect. We are waiting on their resolution of an issue in their SDK.

**Comment by aaronbarnardsound** [comment]
Closing this as Coinbase wallet displays on mobile devices and not desktop devices as expected.
