### ISSUE TITLE
WalletConnect - Error: could not find block

### ISSUE THREAD

**Issue by aaronbarnardsound** [blocknative/onboard#319]
When using WalletConnect, there are periodic errors for "could not find block":
![Screen Shot 2020-04-24 at 9 16 18 AM](https://user-images.githubusercontent.com/29873495/80165048-e6a57c80-861d-11ea-9d05-124cc430f745.png)

The error doesn't seem to affect data lookups or transactions. I believe it is due to infura not supporting subscriptions to new blocks over https.

An issue has been raised on their repo here: https://github.com/WalletConnect/walletconnect-monorepo/issues/256

So we will wait for a resolution on their end.

**Comment by taylorjdawson** [comment]
Tested and this seems to be fixed, closing for now.
