### ISSUE TITLE
Error: Authereum instance destroyed

### ISSUE THREAD

**Issue by aaronbarnardsound** [blocknative/onboard#347]
There might be a possible memory leak with Authereum wallet when switching between wallets. To replicate this issue:  
- Head to the [Onboard demo](https://reactdemo.blocknative.com)
- Click "Select a Wallet"
- Select Authereum and login
- Open up the console
- Then click "Reset Wallet State" which will call the `destroy` method on the Authereum instance
- Then wait for ~30 seconds for the `Error: Authereum instance destroyed` error

@miguelmota Could you take a look at this when you get a chance? Are there any long running polls that possibly aren't being canceled when the `destroy` method is called? You can clone the demo repo [here](https://github.com/blocknative/react-demo) if you want to run it locally.

I have checked the Onboard code by adding logs and Onboard doesn't seem to call any methods on the Authereum provider or instance after the `destroy` method has been called, so I am pretty sure this isn't being caused by Onboard.

**Comment by miguelmota** [comment]
@aaronbarnardsound it indeed was event listeners that weren't removed after the instance was being destroyed. The fixes are in place on authereum sdk version `0.0.4-beta.154`. Thanks!

**Comment by aaronbarnardsound** [comment]
This looks good in version `0.0.4-beta.154` will update in the next release
