### ISSUE TITLE
How to create a WalletCheckModule instance when initializing Onboard?

### ISSUE THREAD

**Issue by troggy** [blocknative/onboard#348]
I'm interested in customizing Modal window for "network" walletCheck. As far as I see, I can [supply a WalletCheckModule instance](https://github.com/blocknative/onboard/blob/master/src/modules/check/index.ts#L12) created with "heading" and "description" options during initialization. But how do I import [network check](https://github.com/blocknative/onboard/blob/master/src/modules/check/network.ts) module into my app to create? It is not publicly exported by bnc-onboard npm package

**Comment by aaronbarnardsound** [comment]
Hey @troggy thanks for pointing this out, there is a problem with our validation and interfaces for customizing the Wallet Check initialization. I am getting this fixed now and will get back to you shortly once the updated code is released and with instructions on how to do this.

**Comment by aaronbarnardsound** [comment]
@troggy A fix was included in Onboard.js version `1.9.1`, so upgrade to that version and then you will be able to customize the wallet check modules via their initialization objects:

```javascript
import Onboard from 'bnc-onboard'

const onboard = Onboard({
  walletCheck: [
    { 
       checkName: 'connect',
       heading: 'Your Custom Heading',
       description: 'Your custom description',
       icon: 'Your custom icon string',
       html: '<p>Some extra custom markup that will be displayed under the description</p>' ,
       button: {
         text: 'Custom button text',
         onclick: () => alert('You clicked the custom button')
       }
    },
    { checkName: 'network' },
    { checkName: 'balance', minimumBalance: '100000' },
  ]
})
```

Let me know if you have any questions!

**Comment by troggy** [comment]
@aaronbarnardsound the new version works great. Thank you :)
