### ISSUE TITLE
Update WalletConnect to 1.0.5

### ISSUE THREAD

**Issue by kartojal** [blocknative/onboard#378]
Hello,

Could you update the WalletConnect provider to the latest version? It is out of beta and now supports WalletConnect directly from Mobile if the user have a WalletConnect wallet installed in their phone, without any desktop.

https://www.npmjs.com/package/@walletconnect/web3-provider

https://twitter.com/pedrouid/status/1273915042287759364?s=20

**Comment by cmeisl** [comment]
@kartojal We're working on this now. WalletConnect's direct use between mobile browser and mobile wallet is very slick.
