### ISSUE TITLE
Ledger Transport

### ISSUE THREAD

**Issue by aaronbarnardsound** [blocknative/onboard#415]
Onboard.js currently defaults to the U2F transport, but this transport is [broken for Windows 10 users](https://www.ledger.com/windows-10-update-sunsetting-u2f-tunnel-transport-for-ledger-devices/).
Instead of defaulting to the U2F transport, we can detect the user's browser/os combination when initializing the Ledger module and dynamically import the ideal transport for that combination. 

The possible scenarios and the corresponding transport: 
- OS: Windows 10, Browser: Firefox | IE -- Display error message informing the user to switch to a compatible browser
- OS: macOS, Browser: Safari | Firefox -- Use U2F transport
-  All other combinations default to using the WebUSB transport

**Comment by btchip** [comment]
That's correct - you can also deal with Linux the same way you'd deal with macOS

Also note that while being more convenient, the U2F tunnel is still a hack, and could be deprecated at any time by the browser implementation. It is also the only transport that can be initialized without a user action on browser (typically clicking a button) - so it'd be a good practice to suggest that the websites require a user action (I believe most do)

**Comment by aaronbarnardsound** [comment]
Thanks for the additional info @btchip. The modal within Onboard.js that allows user's to select a wallet requires a user action, and that is when the transport will be initialized, so we should be all good on that front 👍
