### ISSUE TITLE
pkg squarelink incompatible in lower version browsers

### ISSUE THREAD

**Issue by geraldchen890806** [blocknative/onboard#439]
squarelink.min.js use ...

```
maxBlockRef:function(...e){const` t=r(e);return t[t.length-1]}
```

**Comment by aaronbarnardsound** [comment]
@geraldchen890806 Are you referring to the `const` keyword here? You could use babel to transpile down to es5 compatible code.

**Comment by geraldchen890806** [comment]
@aaronbarnardsound the code is in squarelink.min.js which is in onboard dependencies

"squarelink": "^1.1.4",

**Comment by aaronbarnardsound** [comment]
@geraldchen890806 Yep, you can use babel to transpile the Squarelink module in your `node_modules` folder to be es5 compatible if you need to target that js environment. Check out this thread for more info on targeting node modules with babel: https://github.com/babel/babel-loader/issues/171

**Comment by aaronbarnardsound** [comment]
Closing due to Squarelink being removed from Onboard
