### ISSUE TITLE
Update MetaMask module

### ISSUE THREAD

**Issue by aaronbarnardsound** [blocknative/onboard#445]
We need to update the MetaMask wallet module to allow for the upcoming changes detailed [here](https://docs.metamask.io/guide/provider-migration.html)

**Comment by tuckerchapin** [comment]
With Metmask making breaking changes on Monday I just wanted to follow up here and check that support is good to go for the 16th?

**Comment by aaronbarnardsound** [comment]
@tuckerchapin Yep we just updated in the latest release: https://github.com/blocknative/onboard/releases/tag/1.15.0
