### ISSUE TITLE
Switch from @ledger/hw-transport-u2f

### ISSUE THREAD

**Issue by dasanra** [blocknative/onboard#452]
For more than one year Ledger team has encouraged to use of other connecting solutions like `@ledger/hw-transport-webusb`. With latest Windows 10 update, Ledger devices no longer works on WebApps using `bnc-onboard`.

Check more details here:
https://www.ledger.com/windows-10-update-sunsetting-u2f-tunnel-transport-for-ledger-devices

**Comment by aaronbarnardsound** [comment]
@dasanra We did actually switch over to the webusb transport in this PR: https://github.com/blocknative/onboard/pull/424 but had to revert it back in this PR: https://github.com/blocknative/onboard/pull/432

Switching to the webusb transport actually broke functionality on Windows 10 and we also had reports of problems on other devices as well, whereas we haven't received reports of any problems with the U2F transport (including Windows 10). 

We allow a custom transport to be passed in on initialization of the Ledger wallet module, so devs can decide for themselves if they would like to use a different transport and we feel that this is the best balance at this point in time, but happy to revisit if there have been changes to the webusb transport to make it more stable across devices.

Please check out the code in #424 and if you find that there is something we are missing, then please let me know.
