### ISSUE TITLE
bug: Cannot select wallet address when connect with Ledger

### ISSUE THREAD

**Issue by roy1210** [blocknative/onboard#454]
Hi teams!

The dropdown is not working when wallet connect with `ledger`. Here should be able to select few addresses. 
Much appreciated for your reply :D

Gist: https://gist.github.com/roy1210/4df8d5438d4a081d6d36e770f516ca5d
version: "bnc-onboard": "^1.16.0",

![Screenshot 2020-11-29 at 4 16 40 PM](https://user-images.githubusercontent.com/42575132/100540903-4d0d1000-327b-11eb-80fa-e8d2d6d0d944.png)

**Comment by dasanra** [comment]
I'm having this issue with "bnc-onboard": "1.15.0". Had to rollback to v1.14.0 to fix it.

**Comment by roy1210** [comment]
Hi @dasanra 
Thank you for your advice!
In my case, the issue still exist in v1.14.0 😢 

https://gyazo.com/7dea6fcf3464646df3272d003af81ff2
https://gyazo.com/832e82eb188ca4f50cc9f7d2abe33d9a

**Comment by tuckerchapin** [comment]
I can corroborate with a Nano X and Nano S. The [@ledgerhq/hw-app-eth](https://github.com/LedgerHQ/ledgerjs/tree/master/packages/hw-app-eth) and [@ledgerhq/hw-transport-u2f](https://github.com/LedgerHQ/ledgerjs/tree/master/packages/hw-transport-u2f) seem to be substantially out of date.

**Comment by dasanra** [comment]
I may add that this issue is not only affecting Ledger but also happenning in Trezor.

As mentioned above, `@ledgerhq/hw-transport-u2f` is also causing issues with `ledger` on Windows 10 but this is not related

**Comment by roy1210** [comment]
Looks like my issue has been fixed. Thank you!
![image](https://user-images.githubusercontent.com/42575132/100690058-ba768900-33c0-11eb-838b-3fbde1e123b4.png)
