### ISSUE TITLE
Torus Web3 Type Error

### ISSUE THREAD

**Issue by dmarzzz** [blocknative/onboard#461]
Type error in 'onboard/src/modules/select/wallets/torus.ts(102,40)'. Exported web3 type from Torus is incorrect and does not define an index to select on in the web3.eth.accounts array. 

Specific Error : 

Element implicitly has an 'any' type because expression of type '0' can't be used to index type 'Accounts'.
Property '0' does not exist on type 'Accounts'

**Comment by aaronbarnardsound** [comment]
@YZhenY We have locked the Torus Embed version at `1.8.2` as there seem to have been some breaking changes (sych as removing web3 from the Torus instance) that have been included in subsequent minor releases and it also seems that the types have changed as well. 

When you get a chance could you create a PR that:

- Updates the Torus version to the latest version
- Updates the Torus Onboard module to use the updated methods to get the user's address, network and balance
- Updates the Onboard Torus types to match the Torus internal types

Thanks!

**Comment by YZhenY** [comment]
@aaronbarnardsound 

Please find the PR done by @chaitanyapotti https://github.com/blocknative/onboard/pull/470

Let us know if there are issues

**Comment by dmarzzz** [comment]
Fixed in release 1.17.1
