### ISSUE TITLE
polling interval

### ISSUE THREAD

**Issue by dmarzzz** [blocknative/onboard#466]
<img width="657" alt="Screen Shot 2020-12-15 at 4 56 52 PM" src="https://user-images.githubusercontent.com/22778355/102277636-9190e080-3ef6-11eb-9643-6dc7891a8a9e.png">

Wallet-connect and web3-provider-engine can take in a pollingInterval parameter but onboard has no way to pass one in at the moment.

Functionality that needs to be implemented: Add an optional (blockPollingInterval) parameter to initialization, add to validation and svelte store, and pass it into wallet-connect.ts and providerEngine.ts modules.

**Comment by aaronbarnardsound** [comment]
Closed via #467
