### ISSUE TITLE
Infura key is shown when connect wallet

### ISSUE THREAD

**Issue by roy1210** [blocknative/onboard#479]
HI teams.
I notice our infura key is shown when connect wallet with wallet which required RPC_URL. (Such as `WalletConnect`) 
Is it possible to hide infura key somehow? Please advise. Thank you!

![image](https://user-images.githubusercontent.com/42575132/104675838-35052900-5721-11eb-822f-48cb03254968.png)

**Comment by taylorjdawson** [comment]
Hey @roy1210! Have you tried restricting the origin of the API Key? Or any of the other options discussed [here](https://infura.io/docs/ethereum#section/Project-Security)?

**Comment by roy1210** [comment]
@taylorjdawson 
Cool, thank you for your reply.

I have another question about onboard.js
As per above screenshot, looks like browser is calling `RPC_URL` in every 2 secs if user has chosen `WalletConnect`. Is it possible to reduce this calling? 
(Actually, it is no need to call RPC_URL if using pure [WalletConnect](https://github.com/WalletConnect/walletconnect-monorepo) library)

**Comment by aaronbarnardsound** [comment]
Hey @roy1210 you can reduce the block poll by using the [`blockPollingInterval` Onboard initialization parameter](https://docs.blocknative.com/onboard#blockpollinginterval-optional-default-4000)
