### ISSUE TITLE
send transaction with ERC20 token

### ISSUE THREAD

**Issue by roy1210** [blocknative/onboard#486]
Hi team!
I'd like to have advice about how to interactive with ERC20 token.
I got this error message when choose Metamask as wallet provider. Should I modify 'signer.js' to fix this issue? Currently, I'm using the same code as the example to try to run the `contract.transfer(toAddress, value)`

https://github.com/blocknative/react-demo/blob/master/src/signer.js

![image](https://user-images.githubusercontent.com/42575132/105966796-14918300-60c0-11eb-8980-c64bc872e277.png)

**Comment by aaronbarnardsound** [comment]
Hey @roy1210 I am closing this issue as it isn't an issue with Onboard.js directly. I encourage you to [join our Discord server](https://discord.gg/KZaBVME) to ask for help with general web3 questions :)
