### ISSUE TITLE
Multiple issues when running in the context of an Angular application

### ISSUE THREAD

**Issue by REPTILEHAUS** [blocknative/onboard#495]
Have you got any documentation on how to implement within and Angular application ? 

I get a ton of errors.

```
ERROR in ./node_modules/xhr2-cookies/dist/xml-http-request.js
Module not found: Error: Can't resolve 'http' in 'path/to/app/node_modules/xhr2-cookies/dist'

ERROR in ./node_modules/xhr2-cookies/dist/xml-http-request.js
Module not found: Error: Can't resolve 'https' in 'path/to/app/node_modules/xhr2-cookies/dist'

ERROR in ./node_modules/xhr2-cookies/dist/xml-http-request.js
Module not found: Error: Can't resolve 'os' in 'path/to/app/node_modules/xhr2-cookies/dist'

ERROR in ./node_modules/cipher-base/index.js
Module not found: Error: Can't resolve 'stream' in 'path/to/app/node_modules/cipher-base'

ERROR in ./node_modules/keccak/lib/api/shake.js
Module not found: Error: Can't resolve 'stream' in 'path/to/app/node_modules/keccak/lib/api'

ERROR in ./node_modules/keccak/lib/api/keccak.js
Module not found: Error: Can't resolve 'stream' in 'path/to/app/node_modules/keccak/lib/api'

ERROR in ./node_modules/walletlink/dist/vendor-js/keccak/lib/api/keccak.js
Module not found: Error: Can't resolve 'stream' in 'path/to/app/node_modules/walletlink/dist/vendor-js/keccak/lib/api'

ERROR in ./node_modules/walletlink/dist/vendor-js/keccak/lib/api/shake.js
Module not found: Error: Can't resolve 'stream' in 'path/to/app/node_modules/walletlink/dist/vendor-js/keccak/lib/api'

```

**Comment by aaronbarnardsound** [comment]
Hey @REPTILEHAUS it looks like your build setup is missing the node builtin modules which a lot of the wallets in Onboard require. We don't include those in the Onboard bundle as we don't want projects that are already including them to have them included twice and therefore bloating their bundle. 

Try searching for how to include the node builtin modules with your JS bundler and that should sort it out

**Comment by REPTILEHAUS** [comment]
It seems to be an issue with every multi wallet support library i have tried, it would be better if we didnt have to manage these polyfills or maybe provide a pre-built cdn version for angular cli projects https://github.com/walletlink/walletlink/issues/56

**Comment by aaronbarnardsound** [comment]
Due to the fact that Onboard utilises code-splitting to keep the bundle size as minimal as possible, we can't build a IIFE version of the library to host on a CDN.

Closing this issue as there is no further action to be taken.
