### ISSUE TITLE
Feature Request: Export wallet connector icons

### ISSUE THREAD

**Issue by x48-crypto** [blocknative/onboard#500]
It would be nice if the currently selected wallet module icon was exposed somewhere in the Onboard API.

I would like to show the icon of the currently selected wallet on my wallet connect button.

<img width="791" alt="Screenshot 2021-02-17 at 23 28 53" src="https://user-images.githubusercontent.com/70453354/108306648-3d161580-7172-11eb-806b-c2124fa74dfe.png">

**Comment by x48-crypto** [comment]
test

**Comment by taylorjdawson** [comment]
Hey @x48-crypto! We can definitely add this, putting it on our roadmap now, will post an update here once it is ready
