### ISSUE TITLE
Coinbase wallet says you need to install the app even if you already have it

### ISSUE THREAD

**Issue by juafrapat** [blocknative/onboard#501]
Trying to connect using coinbase wallet shows you a warning saying it's not installed even if it's.

https://user-images.githubusercontent.com/45358012/108606676-accb1100-73bb-11eb-889f-9eef832b051a.mp4

**Comment by aaronbarnardsound** [comment]
@juafrapat Unfortunately there is no way of knowing whether the Coinbase Wallet app is installed from within the browser. When the "install" button is clicked it will take you to the Coinbase wallet if installed, otherwise the app store if not.

**Comment by juafrapat** [comment]
@aaronbarnardsound thanks for the answer, still after clicking on install and opening the app (supposing it's already installed) it doesn't connect to the website.

**Comment by aaronbarnardsound** [comment]
@juafrapat Yes as far as I am aware there is no way of adding a url to the deeplink to get Coinbase wallet to open the app with the app url. Unfortunately there is very little developer documentation for Coinbase wallet. 

I am going to close this issue for the moment, but if you find a way to add a url to the deeplink feel free to create a new issue detailing how that can be done or create a PR to add the new functionality.
