### ISSUE TITLE
Closing metamask while locked, never reopens the windows

### ISSUE THREAD

**Issue by Elyx0** [blocknative/onboard#512]
https://user-images.githubusercontent.com/706218/111898174-d9923880-89fa-11eb-8d22-b1bc0dce1a4d.mp4

Even if I switch wallets, until I physically click top right on my metamask extension to unlock, the dapp will be stuck in this state.

![Screen Shot 2021-03-21 at 3 52 31 AM](https://user-images.githubusercontent.com/706218/111898193-ef9ff900-89fa-11eb-8356-54ebf6c0788e.png)
![Screen Shot 2021-03-21 at 3 51 26 AM](https://user-images.githubusercontent.com/706218/111898194-ef9ff900-89fa-11eb-99fb-a4b5a8281c0a.png)

    "web3": "^1.3.4"
    "bnc-onboard": "^1.20.0",

Tried with 1.19.2 as well

Metamask: 9.2.0 Chrome Mac

Connect does ` Wallet.instance().selectWallet(null);`

**Comment by Elyx0** [comment]
Maybe linked to https://github.com/MetaMask/metamask-extension/issues/10085

**Comment by aaronbarnardsound** [comment]
Yes unfortunately this is a MetaMask issue.

**Comment by taylorjdawson** [comment]
@Elyx0 Closing this as it is related to MM's issue 👍🏾
