### ISSUE TITLE
Trezor confirm modal under BNC onboard modal if adblocker

### ISSUE THREAD

**Issue by Elyx0** [blocknative/onboard#515]
Screenshot to be provided.

**Comment by Elyx0** [comment]
![Screen Shot 2021-03-29 at 7 39 26 PM](https://user-images.githubusercontent.com/706218/112912844-8e48eb80-90c6-11eb-9909-1d7064157bba.png)
![Screen Shot 2021-03-29 at 7 39 11 PM](https://user-images.githubusercontent.com/706218/112912850-90ab4580-90c6-11eb-9e16-75f595702a5a.png)

**Comment by aaronbarnardsound** [comment]
Hey @Elyx0 you can override the `z-index` property of the Onboard modals by adding the following css to your project:

```css
.bn-onboard-custom.bn-onboard-modal { z-index: 1; }
```

I am not sure what the `z-index` value of the Trezor popup is, so you might need to modify the above value to suit.

Let me know if that fixes it for you.

**Comment by taylorjdawson** [comment]
@Elyx0 Did that solve your issue? Closing for now please re-open if this issues persists.
