### ISSUE TITLE
Use with web3-react or ethers.js

### ISSUE THREAD

**Issue by noobshow** [blocknative/onboard#547]
Is there any possibility of mixing this with ethers.js or web3-react?

I use those two internally in my project, but loved the modal UI onboard

**Comment by taylorjdawson** [comment]
Hey @noobshow! Could you elaborate as to what your use case is?

**Comment by noobshow** [comment]
I have dependencies on useWeb3React for various wallet related uses on my dapp and seeing web3-react doesn't come with those beautifully themed pop up modals, I thought why not use onboard to get the user to select their connector, then internally I route it with web3-react library which seems to be based on ethers.js

**Comment by noobshow** [comment]
I noticed this depends on web.js library and not ethers.js which seems weird(to me) since this library seems to be written in typescript and ethers.js is fully typesafe and maybe the popular choice these days.

**Comment by taylorjdawson** [comment]
Well what you could do use use onboard.js to get the provider from the wallet and just pass that provider to ethers.js and skip web3-react? Or pass the provider from onboard.js to web3-react?

**Comment by taylorjdawson** [comment]
I can't speak to why web3 was chosen over ethers.js as I wasn't involved in that decisions although I would agree that ethers.js has become quite popular and the typesaftey is nice. If we were to revamp onboard.js in the future I am sure we would at least consider using etherst.js

**Comment by noobshow** [comment]
Is that like possible?

That's my intentions, just still reading the Codebase to see what's exposed to the public for such capabilities.

I know when it connects, I can get the account, network, but the provider? I'm searching for that...

**Comment by noobshow** [comment]
`import Onboard from 'bnc-onboard'
import Web3 from 'web3'

let web3;

const onboard = Onboard({
  dappId: apiKey,       // [String] The API key created by step one above
  networkId: networkId  // [Integer] The Ethereum network ID your Dapp uses.
  subscriptions: {
    wallet: wallet => {
       web3 = new Web3(wallet.provider)// will this provider work with ethers.js or web3-react? 
    }
  }
});
`

**Comment by taylorjdawson** [comment]
Yea it totally should, try it out! 👍🏿

**Comment by noobshow** [comment]
Thanks, was editing the code syntax on mobile before seeing you did that...

I will try it out, thanks.

**Comment by taylorjdawson** [comment]
If this works for you let me know so I can close the issue, or you can just close it yourself once you get it working

**Comment by noobshow** [comment]
Doesn't seem to be a Web3Provider, couldn't find anything to wrap it with through ethers.js or web3-react

**Comment by taylorjdawson** [comment]
Can you show an example of what's not working?

**Comment by noobshow** [comment]
I tried making this changes, i might be doing it wrong...

Not used to any of these libraries, started trying them like 3-4 days ago... 

> ```js
> import Onboard from 'bnc-onboard'
> //import Web3 from 'web3'
> 
> let web3;
> 
> const onboard = Onboard({
>   dappId: apiKey,       // [String] The API key created by step one above
>   networkId: networkId  // [Integer] The Ethereum network ID your Dapp uses.
>   subscriptions: {
>     wallet: wallet => {
>       let provider = new ethers.providers.Web3Provider(wallet.provider);
>           activate(wallet.provider);// comes from     const {connector, active, activate } = useEthers();
>       // web3 = new Web3(wallet.provider)// will this provider work with ethers.js or web3-react? 
>     }
>   }
> });
> ```

**Comment by noobshow** [comment]
I guess it can't be solved?

**Comment by taylorjdawson** [comment]
Hey @noobshow I think this can be done so I re-opened it, could you list any error that you see in the console when trying to initialize?

**Comment by noobshow** [comment]
hmm, I would do that in the morning... I think the only think lacked is getting the provider to be injected or connected to ethers.js or web3-react

**Comment by taylorjdawson** [comment]
Yeah this should definitely work the way you have it so interested in seeing that the issue is

**Comment by noobshow** [comment]
I will try running a debug/test project during the weekend as I seem to have a believe it should work with ethers.js and web3-react

**Comment by taylorjdawson** [comment]
@noobshow For reference could you outline the issues you were having and include the error logs?

**Comment by noobshow** [comment]
Not a particular error per se, its more of trying to figure out where/how to link the provider it returns with that allowed by ethers.js and/or web3-react

**Comment by taylorjdawson** [comment]
@noobshow Also what wallet are you using? I have also sometimes have had issues with a specific wallet's provider

**Comment by noobshow** [comment]
I was using plain MetaMask to run my tests... Which should be an InjectedConnector

**Comment by noobshow** [comment]
This library was developed with beauty in mind, i wish i could use it but many of the dependencies aren't what the world is using right now...

Wish i could use it

**Comment by taylorjdawson** [comment]
@noobshow by the way we don't use web3 or ethers as we just provide you with the wallet's provider, just to clarify

**Comment by taylorjdawson** [comment]
@noobshow what deps are you referring to? We would love to know how we could improve onboard for you, we take feedback seriously 👍🏿

**Comment by noobshow** [comment]
I'm thinking it should be open to using ethers.js and web3.js by default, I don't really know how but I've seen some project do that... 

> @noobshow by the way we don't use web3 or ethers as we just provide you with the wallet's provider, just to clarify

Yea, I figured the dependency isn't directly web3.js,its Web3ProviderEngine.

**Comment by noobshow** [comment]
> @noobshow what deps are you referring to? We would love to know how we could improve onboard for you, we take feedback seriously 👍🏿

Many of it seems to be listed in a issue I opened today, seems they are abandoned... e.g Web3ProviderEngine - 7 months ago with various vulnerabilities unfixed

**Comment by noobshow** [comment]
I wish I could help with some fixes and upgrading so I can use this, just hooked up with some months worth of projects.

**Comment by taylorjdawson** [comment]
Right the #548 issue you opened, so essentially you could use this if we update some of the deps? Just trying to get a feel for  what issues with onboard are obstacles.

**Comment by noobshow** [comment]
The dependencies and a common interface between ethers.js and web3.js.

My dapp project is in progress and we want to support almost all of the wallets included in this library..

**Comment by taylorjdawson** [comment]
I think it isn't our deps but the deps that our deps depend on, for instance [web3-provider-engine](https://github.com/MetaMask/web3-provider-engine#readme) last commit was 7 days ago so I wouldn't exactly call it abandoned. 

@noobshow If you haven't already [join our discord](https://discord.gg/URYMdY94) after which please send me a DM so I can help support you further.

**Comment by noobshow** [comment]
Their last release was 7 months ago according to npm. 

yea I saw the security issues are dependencies of dependencies and they seems much(probably around 30 issues) that it might take longer time for the libraries to be updated or some might even be replaced too...

Security wise, that's a big risk as any of these issues might be used in attacking my user's clients(browsers and eventually devices).

Will check out the discord..

Thanks for the support

**Comment by noobshow** [comment]
Does this library on connect show the connector name?
Either Injected, fortmatic, etc?

I figured if I have the name, I could just use the activate function on the Injector on web3-react/ethers.js

**Comment by noobshow** [comment]
I will try test that out today and feed you back if it works, I think it would...

**Comment by noobshow** [comment]
The dependencies update or fixing the various issues with them would be the only problem if that works

**Comment by noobshow** [comment]
> Does this library on connect show the connector name?
> Either Injected, fortmatic, etc?
> 
> I figured if I have the name, I could just use the activate function on the Injector on web3-react/ethers.js

According to this line, it is proven that onboard.js declare the wallet.name and can be used as such to be reconnected in ethers.js activate(connector).

Its weekend, been unable to run thorough tests, but codes in the wild proved it should work that way...

**Comment by taylorjdawson** [comment]
@noobshow are you asking if onboard exposes the name of the wallet? What's the activate function? And I guess generally what are you trying to accomplish?

**Comment by noobshow** [comment]
Was able to make it work, but most of the work was behind the scene...

**Comment by paulrberg** [comment]
Hey @noobshow, I am interested in your set up (exposing the onboard.js UI to the user but using web3-react under the hood).

Can you share a link to your project?

**Comment by paulrberg** [comment]
> If we were to revamp onboard.js in the future I am sure we would at least consider using ethers.js

This would be amazing. The fact that ethers.js is not supported is the only thing holding me back from switching to blocknative.

**Comment by noobshow** [comment]
> Hey @noobshow, I am interested in your set up (exposing the onboard.js UI to the user but using web3-react under the hood).
> 
> Can you share a link to your project?

Its currently private repository for now, until the in-house development is over...

I have a way around using ethers.js as explained above, I haven't had the chance to get back to using onboard.js for now...

If you need a heads up, the big part of it is you just get the onboard.js connected `wallet.name` and check a enum of connector you have on record if such name exist, then use ethers.js `activate(connector) ` to activate it with ethers.js.

Done.

**Comment by paulrberg** [comment]
Ah okay, thanks for the tip, @noobshow!

As a side-note, I looked at Blocknative's [react-demo](https://github.com/blocknative/react-demo). It looks like they are using ethers.js there, not web3.js

**Comment by taylorjdawson** [comment]
Hey @paulrberg 👋 as you saw with the react-demo, onboard does work with ethers.js -- if you have any specific issues integrating feel free to reach out on our discord 👍

**Comment by paulrberg** [comment]
Thanks @taylorjdawson!

**Comment by theurgi** [comment]
This is great news to find out that ethers.js is supported. 

web3 is [extremely heavy](https://bundlephobia.com/package/web3@1.6.1) for the client and doesn't treeshake—ethers does.

One request would be to add ethers support to the docs—I wouldn't have known it was an option if I didn't search for this issue.
