### ISSUE TITLE
Allow changing network name

### ISSUE THREAD

**Issue by dzek69** [blocknative/onboard#556]
via `onboard.config()` i can change networkId to support multiple networks in my app, but I cannot change networkName using this method

this way wrong network name may be suggested to my users when `You must change networks` modal appears.

Please add support for changing networkName config

**Comment by taylorjdawson** [comment]
Hey @dzek69 👋🏾 , As it stands the best way to change the `networkId` and the `networkName` is to reinitialize onboard.js with the new `networkName`, `networkId` and then to change any rpc urls to that new network. This is due to the fact that only some of the wallets support network switching. 

In the future we may support this as a method but for now reinitializing can offer the same outcome.

**Comment by dzek69** [comment]
Isn't reinitializing resulting in console error/warning about onboard being already initialized?

Initializing looks like kind of Singleton to me

Or this is just a warning and it will actually be initialized with different settings, not returning the same instance every time?

**Comment by taylorjdawson** [comment]
@dzek69 Yup! You can safely ignore it. If you go to [Mempool Explorer](https://explorer.blocknative.com/?v=1.20.4&0=ethereum&1=main&s=%7B%22name%22%3A%22Curv.fi%22%2C%22address%22%3A%220xdf5e0e81dff6faf3a7e52ba697820c5e32d806a8%22%7D&s=%7B%22name%22%3A%22Balancer%22%2C%22address%22%3A%220x3e66b66fd1d0b02fda6c811da9e0547970db2f21%22%7D&s=%7B%22name%22%3A%22Uniswap+v2+Router%22%2C%22address%22%3A%220x7a250d5630b4cf539739df2c5dacb4c659f2488d%22%7D&s=%7B%22name%22%3A%22SushiSwap+Router%22%2C%22address%22%3A%220xd9e1ce17f2641f24ae83637ab66a2cca9c378b9f%22%7D&fr=%7B%22status%22%3A%22pending%22%7D), open the console, and then switch networks, you'll see the same warning as this is how we also change networks with onboard.

**Comment by dzek69** [comment]
okay, thank you!

**Comment by taylorjdawson** [comment]
@dzek69 Yea! Don't hesitate to reach out if you need anything else! And be sure to join our [Discord](https://discord.gg/S3ycZNtG) if you haven't already 🤘
