### ISSUE TITLE
Ledger not working on Chrome v91

### ISSUE THREAD

**Issue by taylorjdawson** [blocknative/onboard#577]
Chrome v91 broke U2F support of Ledger. See [brave issue](https://github.com/brave/brave-browser/16204).

**Comment by tuckerchapin** [comment]
Is the path forward looking like a mix of U2F and WebUSB support depending on the client browser or the Ledger Live bridge?

**Comment by taylorjdawson** [comment]
@tuckerchapin Yes, essentially if your browser supports WebUSB then that will be used otherwise it will use u2f. If you have any suggestions/requests feel free to leave them here! 👍🏾

**Comment by siibars** [comment]
Hello @taylorjdawson  thank you for addressing this 🙏
When would it be possible to release it ?

**Comment by taylorjdawson** [comment]
@siibars We are targeting tomorrow morning June 15th

**Comment by taylorjdawson** [comment]
Fixed in #588!
