### ISSUE TITLE
Add data attributes option to be added to wallets option buttons

### ISSUE THREAD

**Issue by carlos0202** [blocknative/onboard#581]
I'm trying to run e2e tests to a given Dapp, but I cannot get a good unique identifier for each wallet displayed during `walletSellect()` flow. The only options available are as follows:
![image](https://user-images.githubusercontent.com/8674703/121571924-a061d700-c9f1-11eb-830c-0e2a97be299d.png)

Can we have a way to specify custom data attribute that can make it easier to run consistent tests without worrying about selectors being too brittle?
![image](https://user-images.githubusercontent.com/8674703/121572287-ff275080-c9f1-11eb-9d15-a027292c8ebe.png)

Thanks in advance for helping me out with this!

**Comment by taylorjdawson** [comment]
Hey @carlos0202 👋 is it possible to just use the `label` field?

**Comment by carlos0202** [comment]
> Hey @carlos0202  is it possible to just use the `label` field?

Basically no, as there could be any other element inside the DOM with the same text. What we usually need is to uniquely identify an element while running e2e tests, and in this case, there's no really good unique selector for each button.

**Comment by taylorjdawson** [comment]
Why not set the label to a `uuid`?

**Comment by taylorjdawson** [comment]
@carlos0202  I think this can be accomplished by overriding the wallet label with a uuid for instance:
```ts
import { v4: uuid } from 'uuid'
import Onboard from 'bnc-onboard'
import Web3 from 'web3'

let web3;

const onboard = Onboard({
  dappId: apiKey, 
  walletSelect: {
    wallets: [
       { walletName: 'metamask', label: uuid() }
      //... do the same for every other wallet you want to test
    ]
  }
});
```
