### ISSUE TITLE
bug: Not able to connect to Yearn finance with XDEFI Wallet

### ISSUE THREAD

**Issue by Batmine** [blocknative/onboard#597]
[**Describe the bug**](url)
Not able to connect to Yearn finance with XDEFI Wallet 

[**To Reproduce**](url)
1. Go to 'Yearn finance' https://yearn.finance/
2. Click on "Connect Wallet" and choose Metamask 
3. See error

[**Expected behavior**](url)
I can connect to Yearn finance with XDEFI Wallet 

[**Screenshots**](url)

https://user-images.githubusercontent.com/83281521/123955843-c2c49000-d9b2-11eb-991e-32813df7513f.mov

[**Hardware** ](url)
- [x] PC
- [x] Mac
@davidp94 @liamaharon

**Comment by cmeisl** [comment]
Yearn's configuration for Onboard does not include XDEFI. They need to include XDEFI in the configuration passed to Onboard initialization.

An example configuration with both MetaMask and XDEFI can be seen here: https://github.com/blocknative/react-demo/blob/master/src/services.js and demoed here: https://reactdemo.blocknative.com/
