### ISSUE TITLE
Liquality: Provider not detected

### ISSUE THREAD

**Issue by cakesoft-pratik** [blocknative/onboard#598]
Onboard not able to detect installed liquality wallet.

**Comment by monokh** [comment]
hi @cakesoft-pratik 
`window.ethereum` should work. It's just that it's not enabled by default. You have to switch it on in Settings
We will enable by default in the next release

The issue with `window.eth`, is that it is restricted to the ethereum mainnet only. So if `window.eth` is used, onboard will not work for other chains like BSC, Polygon or RSK

**Comment by taylorjdawson** [comment]
@monokh Thanks for clarifying this! 👍🏾 
@cakesoft-pratik Closing for now, re-open if your issue isn't completely resolved.
