### ISSUE TITLE
No way to exit Ledger/Trezor Wallet connection if user cancels

### ISSUE THREAD

**Issue by undfined** [blocknative/onboard#601]
Currently, if the user bails on connecting either the ledger or trezor bridge the Onboard dialogue always displays "checking wallet..." and there is no way for the user to select a different wallet without clearing the correct key in localstorage. There should be a way for the user to select a different wallet without clearing localstorage.

![image](https://user-images.githubusercontent.com/954432/124521085-372c7400-dda3-11eb-907d-fa143d1ec152.png)

**Comment by taylorjdawson** [comment]
@undfined Which localstorage key do you have to clear?

**Comment by taylorjdawson** [comment]
@undfined Closing until we get more info. Onboard only uses localstorage for TOS agreements I think this may be a dApp issue.
