### ISSUE TITLE
Unhandled exception when user aborts WalletConnect setup and immediately selects another wallet

### ISSUE THREAD

**Issue by undfined** [blocknative/onboard#602]
Steps to repro:

1) Open wallet select modal
2) Select WalletConnect
3) Exit QR code modal (without connecting)
4) Open Wallet Select modal
4) Select MetaMask wallet (or any other than WalletConnect)
5) See stack trace in console:

```
index.ts:107 Uncaught (in promise) Error: Missing or invalid topic field
    at SocketTransport.send (index.ts:107)
    at WalletConnect.<anonymous> (index.ts:780)
    at Generator.next (<anonymous>)
    at fulfilled (tslib.es6.js:73)
```

**Comment by taylorjdawson** [comment]
@undfined Thanks for raising this issue, I was able to discover another a bug in the process. I'll let you know once it's resolved, probably next week.

**Comment by kingsley1996** [comment]
I also got the same error, has it been fixed?

**Comment by taylorjdawson** [comment]
@kingsley1996 This doesn't affect usability, however, [this issue](https://github.com/blocknative/onboard/issues/241) does affect usability but is a Walletconnect issue not onboard.

**Comment by taylorjdawson** [comment]
Closing as this issue related to #241

**Comment by Dinuz** [comment]
@taylorjdawson you get the same error also if you disconnect from the app. In my case I connect using WalletConnect, I get the QR code and I scan it with my mobile app for Trust Wallet. The connection works great and everything is smooth.
However if I use the same mobile app to disconnect the wallet, it disconnect on the web but in console I get the error:

<img width="1406" alt="Screen Shot 2022-12-08 at 5 43 54 PM" src="https://user-images.githubusercontent.com/1139472/206582844-53efbb0d-dd2c-4f0a-b154-f548fdff31a1.png">

How I can handle this?
