### ISSUE TITLE
Allow to manually define if given wallet should be visible on mobile or not

### ISSUE THREAD

**Issue by dzek69** [blocknative/onboard#605]
I want to block use of MetaMask Mobile, as it's currently really bugged and causes bad experience for my users.

Desktop/extension version is okay, so I want to keep it.

From what I understand from the docs - this is currently not possible.

Can you please add such option?

**Comment by taylorjdawson** [comment]
I like this idea, I'll discuss internally then update if we plan to implement this, thanks!

**Comment by taylorjdawson** [comment]
In the mean time you can do this:
```js
const isMobile = () =>
  /Mobile|Android|iP(hone|od)|IEMobile|BlackBerry|Kindle|Silk-Accelerated|(hpw|web)OS|Opera M(obi|ini)/.test(
    navigator.userAgent
  )

const metamaskWallet = isMobile
  ? [{ walletName: 'metamask', preferred: true }]
  : []

const wallets = [
  ...metamaskWallet
  // ... rest of wallets
]

const onboard = Onboard({
  dappId: apiKey, // [String] The API key created by step one above
  networkId: networkId, // [Integer] The Ethereum network ID your Dapp uses.
  subscriptions: {
    wallet: wallet => {
      web3 = new Web3(wallet.provider)
    }
  },
  walletSelect: {
    wallets: wallets
  }
})
```

**Comment by dzek69** [comment]
Thanks, this is similar to what I did currently as a workaround, but I'd be nice to have this nicely configurable :)

**Comment by taylorjdawson** [comment]
@dzek69 Another issue is that the user can still use walletconnect to connect to your dapp with Metamask still, so it wouldn't work 100%. Had you accounted for that?

**Comment by dzek69** [comment]
thanks for pointing that out 👍🏻 

wallet connect seems to be one of the things that are currently broken there 😄 Anyway, I may not be able to prevent 100% of my users from using bugged apps, but I do what I can :)

**Comment by taylorjdawson** [comment]
@dzek69 Added #654 in latest [release](https://github.com/blocknative/onboard/releases/tag/1.34.0)
