### ISSUE TITLE
Error: desktop is not a valid parameter for walletInitObject

### ISSUE THREAD

**Issue by paulrberg** [blocknative/onboard#617]
## Description

I am defining my wallet list like this:

```ts
import { WalletInitOptions, WalletModule } from "bnc-onboard/dist/src/interfaces";

const wallets: Array<WalletModule | WalletInitOptions> = [
  { desktop: false, preferred: true, walletName: "metamask" },
  {
    desktop: true,
    infuraKey: getEnvVar("REACT_APP_INFURA_API_KEY"),
    preferred: true,
    walletName: "walletConnect",
  },
  {
    desktop: true,
    rpcUrl,
    walletName: "ledger",
  },
];
```

But when I pass this to the `Onboard` constructor, I am getting the following error:

```
Error: desktop is not a valid parameter for walletInitObject, must be one of the following valid parameters: walletName, apiKey, networkId, infuraKey, rpc, bridge, preferred, label, iconSrc, svg, appUrl, email, rpcUrl, LedgerTransport, buildEnv, buttonPosition, enableLogging, loginMethod, loginConfig, showTorusButton, modalZindex, integrity, whiteLabel, appName, appLogoUrl, enabledVerifiers, disableNotifications, rpcUri, webUri, xsUri, blockedPopupRedirect
```

## Environment

- bnc-onboard@npm:1.30.0
- typescript@4.3.5

**Comment by taylorjdawson** [comment]
Hey @paulrberg 👋

So you are mixing 2 types `WalletModule` and `WalletInitOptions`. You can see the validation here on [these lines](https://github.com/blocknative/onboard/blob/d0992ddeba27e91e2ff1b1494b98b68552fe4f44/src/validation.ts#L278-L284).

The `WalletInitOptions` doesn't have the `desktop` field but the `WalletModule`does.

**Comment by paulrberg** [comment]
If I remove `WalletInitOptions`, then I can't pass the `appUrl`, `infuraApiKey`, `rpcUrl` and `walletName` fields.

Any advice on how I could use both types together, correctly? Maybe some union type?

**Comment by taylorjdawson** [comment]
@paulrberg Just remove the `desktop: true` parameter and it should work 👍🏾

**Comment by paulrberg** [comment]
okay!

**Comment by taylorjdawson** [comment]
Closing, please reopen if you have any further issues 👍🏾
