### ISSUE TITLE
Bug: Changing network while connected with WalletConnect not working

### ISSUE THREAD

**Issue by nicosampler** [blocknative/onboard#622]
I've found a problem, while I'm connected to WalletConenct network subscription is not being called when I change the network in my wallet. It does work if I'm connected with MetaMask directly.

Steps to reproduce:
1. I have MM on my phone
2. I connect through WC to my MM 
3. I change from Ethereum Mainnet to Ethereum Optimism
4. network subscription is never called.

The same steps work fine if I connect directly with my MM browser extension.

**Comment by taylorjdawson** [comment]
@nicosampler Unfortunately this appears to be a [Metamask Mobile issue](https://github.com/WalletConnect/walletconnect-monorepo/issues/513) :/

I will let them know to see if they can resolve this.
