### ISSUE TITLE
Problem: moving among pages in nextjs kills WC sesion

### ISSUE THREAD

**Issue by nicosampler** [blocknative/onboard#623]
I'm running a dApp with nextjs and I just founded a problem, seems like when moving from one page to another onboard detects the dApp is being closed and kills WC session.

I've tried locally deleting this line and everything works as expected https://github.com/blocknative/onboard/blob/develop/src/modules/select/wallets/wallet-connect.ts#L109.

do you think is it possible to find a workaround for this problem? I think that killing WC session should be something optional for each dApp.

**Comment by taylorjdawson** [comment]
@nicosampler With nextjs are you doing server side or client side routing?

**Comment by nicosampler** [comment]
Hi @taylorjdawson  client side

**Comment by taylorjdawson** [comment]
@nicosampler Where in your codebase are you creating your Onboard instance? Make sure you have it globally in memory otherwise if the component get's unmounted/destroyed then remounted onboard will re-init and kill the session.

**Comment by nicosampler** [comment]
@taylorjdawson 🍻. 
thx!

**Comment by Msordet** [comment]
Hey @taylorjdawson!
It is still annoying as any rerender of the App component will crash the app.
I'm having an issue with this combined with i18n through `next-i18next` where switching the locale rerenders the App component thus crashing the app.
Have to revert back to 1.29 just for this. :(

**Comment by taylorjdawson** [comment]
@Msordet Onboard can be defined outside of any component. v1.30 adds clean up to prevent memory leaks. For best practices and performance reasons it is highly recommended that you change your implementation and switch back to v1.30 and define your Onboard instance outside of any component in some global state.

**Comment by nicosampler** [comment]
@Msordet you could also try adding a customWallet, just copy the walletConnect current implementation and remove `provider.wc.killSession()`. I've tried to do it but for some reason, it was not adding the new customWalletConnect to in `selectModal`.

**Comment by Msordet** [comment]
Ended up using a HOC around the app so it's all fine now but rather breaking for a minor change. ^^'

**Comment by taylorjdawson** [comment]
Having onboard in global state is best practice. The onboard instance should not exist within a component that's an anti-practice IMO.
