### ISSUE TITLE
Issue: imToken wallet not showing on UI

### ISSUE THREAD

**Issue by kingsley1996** [blocknative/onboard#631]
I have added 'imToken' as an option to connect the wallet but it doesn't appear in the modal. Is there anything special here?

**Comment by kingsley1996** [comment]
I found out 'imToken' wallet only shows on mobile, how can i display it on desktop

**Comment by taylorjdawson** [comment]
@kingsley1996 As far as I know it is a mobile app so you can't use it on desktop. You would want to use WalletConnect 👍🏾
