### ISSUE TITLE
Can't pass metamask qr code scan with walletConnect

### ISSUE THREAD

**Issue by burakakca** [blocknative/onboard#645]
I tested on reactdemo.blocknative.com and mostly doesn't appear some times like 10 min later notifications comes to my phone screen. Why is slow ?.  But https://example.walletconnect.org/ this works fine

**Comment by taylorjdawson** [comment]
@burakakca I am not able to reproduce this issue. It could possibly be related to your network speed. Let me know if this issue persists and feel free to re-open.

**Comment by makoto** [comment]
Walletconnect had performance issues and they switched to new infrastructure which needs upgrade on walletconnect version. Maybe that's the issue? https://twitter.com/WalletConnect/status/1426226788515078144

**Comment by burakakca** [comment]
@makoto yes you are right, that's why, with version 1.34.1, my problem was solved.
