### ISSUE TITLE
Adding node.js built-ins as a dependency should be considered a breaking (major) change

### ISSUE THREAD

**Issue by mds1** [blocknative/onboard#650]
In [v1.31.0](https://github.com/blocknative/onboard/releases/tag/1.31.0) ENS support was added. This version added `@ensdomains/ensjs` as a dependency to onboard.js, and was treated as a minor version bump to v1.31.0.  When upgrading our onboard.js package from 1.27.0 to the latest version, it turns out that v1.31.0 introduced a breaking change for us, because `@ensdomains/ensjs` seems to rely on the `global`, `process.env`, and `Buffer` node.js builtins.

Many build tools such as Webpack v4 automatically polyfill these node modules, but newer build tools such as [Webpack v5](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed) and [Vite](https://vitejs.dev/) do not—they require explicit polyfills during the build step. Many devs try to avoid relying on node.js packages that require polyfills for the browser, but it's understandable that we are unable to do that entirely since onboard.js has dependencies that rely on many of these, including `crypto`, `http`, and `https`

However, I think it's worth considering the addition of node builtins as a breaking change because onboardjs is designed for a browser, and many browser build tools do not polyfill these builtins. Therefore anyone using Webpack v5 or Vite will likely have their app broken when upgrading to v1.31.0 or later (unless they already have those builtins polyfilled), and if they jump ahead by many minor versions, it can be hard to track down which version introduced this breaking change

**Comment by taylorjdawson** [comment]
@mds1 Thank you for this feedback. I agree with you as with ens support we did not make it opt-in. However, I am curious to know if you are building Onboard.js ad including hardware wallets as those wallets will also not build unless you are using Webpack v4.

Which build tool are you using?

**Comment by mds1** [comment]
We are using Vite as the build tool. Right now the current list of selected wallets in this particular app is metamask, walletConnect, torus, ledger, lattice, though admittedly that's just a default set and we haven't tested any of them yet aside from MetaMask.

I did need to add polyfills for [various modules](https://github.com/dcgtc/dgrants/blob/97a360425d07b2899e32a8eafea96655b8486d89/app/vite.config.ts#L11-L16) to get things up and running, though it's possible I'm missing some additional polyfills given that we haven't actually started testing wallets yet. 

In this particular case we already handle ENS resolution on our own and therefore don't need the onboard.js ENS functionality, so it is a bit frustrating to be stuck at v1.30.0. For any features, fixes or new wallets we want to support, we'll have to polyfill node.js built-ins that we don't use, which adds bloat to the bundle size and isn't ideal from a security perspective 😕

**Comment by taylorjdawson** [comment]
@mds1 I know it isn't the exact solution you were anticipating, however, to improve your client side bundle size, I made ENS a dynamic import such that it will not get included in the final build should you decided not to use that feature.

In the future we hope to make Onboard more modular where you can choose which features you would like to be included in your build rather than needing to install everything.

Please let me know if this at least partially solves your issue and feel free to re-open this issue if need be. 

Also if you need any assistance with your build configuration don't hesitate to reach out on [discord](https://discord.gg/gu22vUb7xE) and DM me.

**Comment by mds1** [comment]
Awesome, thanks a lot @taylorjdawson—I'll give that a try soon and ping you on Discord if there's any issues.

Also, a more modular Onboard sounds awesome. Excited to hear that!
