### ISSUE TITLE
Support Arbitrum network.

### ISSUE THREAD

**Issue by GuruJustin** [blocknative/onboard#651]
Is there anyone who knows the way to config the Onboard to support the Arbitrum network on metamask and Trustwallet?

Is this possible with current version? I can see only some specific networkIds are available for now.

**Comment by taylorjdawson** [comment]
@GuruJustin You should be able to pass in the Arbitrum `networkId` and the `networkName` as shown [here](https://docs.blocknative.com/onboard#customizing-unknown-network-name).

```js
const onboard = Onboard({
  // ... other init options
  networkId: 421611,
  networkName: 'arbitrum'
})
```

That `networkId` will get passed to which ever wallet the user selects.

For hardware wallets, you'll most likely need to utilize the custom network feature as shown [here](https://docs.blocknative.com/onboard#hardware-wallet-custom-networks) in our docs.

Let me know if that helps!
