### ISSUE TITLE
Getting an error while connecting Ledger on Electron app

### ISSUE THREAD

**Issue by 0xMars4204** [blocknative/onboard#664]
I'm getting an error while trying to connect Ledger on Electron.

Here's the option for Ledger.

```
import TransportNodeHid from '@ledgerhq/hw-transport-node-hid'
...

return Onboard({
    ...
    walletSelect: {
        wallets: [
            {
                walletName: 'ledger',
                rpcUrl,
                LedgerTransport: TransportNodeHid,
            }
            ...
        ],
    }
})
```

Any help would be appreciated.

![image](https://user-images.githubusercontent.com/83092433/129526696-bc6b5c1a-4f2d-47f0-b0e2-17e3d16a72bb.png)

**Comment by taylorjdawson** [comment]
@0xMars4204 Did you get this fixed yet?

**Comment by 0xMars4204** [comment]
> @0xMars4204 Did you get this fixed yet?

Yeah, it is fixed.
