### ISSUE TITLE
Svelte App build error

### ISSUE THREAD

**Issue by zapaz** [blocknative/onboard#667]
Building Svelte App with rollup fails, even with example (https://codesandbox.io/s/jekzo)

First error : 
```
$ npm run build 
...
[!] Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
node_modules/.pnpm/@ensdomains+ens@0.4.3/node_modules/@ensdomains/ens/build/contracts/ENS.json (2:16)
1: {
2:   "contractName": "ENS",
                   ^
3:   "abi": [
4:     {
Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)

```

After adding @rollup/plugin-json , new error : 
```
[!] Error: 'toBuffer' is not exported by node_modules/.pnpm/ethereumjs-util@7.1.0/node_modules/ethereumjs-util/dist/index.js, imported by node_modules/.pnpm/bnc-onboard@1.31.0/node_modules/bnc-onboard/dist/esm/index-9156d65a.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules/.pnpm/bnc-onboard@1.31.0/node_modules/bnc-onboard/dist/esm/index-9156d65a.js (35:9)
33: import 'bowser';
34: import '@ensdomains/ensjs';
35: import { toBuffer } from 'ethereumjs-util';
             ^
36: var HANDLE_PIN_PRESS = 'handlePinPress';
37: var BUTTON_COLOR = "#EBEBED";
```

**Comment by taylorjdawson** [comment]
@zapaz What does your rollup config look like?

**Comment by zapaz** [comment]
here it is :

```
// this file will not afect the sandbox but will
// afect the deployment and dowload

import svelte from "rollup-plugin-svelte";
import resolve from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import json from "@rollup/plugin-json";
import { terser } from "rollup-plugin-terser";
import css from "rollup-plugin-css-only";
import nodePolyfills from "rollup-plugin-node-polyfills";

const production = !process.env.ROLLUP_WATCH;

export default {
  input: "index.js",
  output: {
    sourcemap: true,
    format: "esm",
    name: "app",
    file: "public/bundle.js",
  },
  plugins: [
    svelte({
      compilerOptions: {
        dev: !production,
      },
    }),
    css({ output: "public/bundle.css" }),

    // If you have external dependencies installed from
    // npm, you'll most likely need these plugins. In
    // some cases you'll need additional configuration —
    // consult the documentation for details:
    // https://github.com/rollup/rollup-plugin-commonjs
    resolve({
      browser: true,
      preferBuiltins: true,
    }),
    commonjs({
      namedExports: {
        "u2f-api": ["sign", "isSupported"],
      },
    }),
    nodePolyfills(),
    json(),

    // If we're building for production (npm run build
    // instead of npm run dev), minify
    production && terser(),
  ],
};
```

**Comment by davidcallanan** [comment]
I am having a similar error with SvelteKit: https://stackoverflow.com/questions/69302056/sveltekit-cannot-import-onboard-js?noredirect=1#comment122564637_69302056

I have also tried modifying the rollup configuration.

Maybe it's a problem with Svelte and not this package though.

**Comment by xpluscal** [comment]
@taylorjdawson is there a realistic way to get onboardjs to work with a sapper application?
The rollup build suggestions don't really apply when using sapper.

Help appreciated! Thx

**Comment by davidcallanan** [comment]
@xpluscal  If you can't get a solution, you could consider switching to [`Web3Modal`](https://github.com/Web3Modal/web3modal), which is working well for me so far.

**Comment by zapaz** [comment]
> @xpluscal If you can't get a solution, you could consider switching to [`Web3Modal`](https://github.com/Web3Modal/web3modal), which is working well for me so far.

did the same ! 

but it's a pity not beeing able to use onboard with Svelte ;-(

**Comment by aaronbarnardsound** [comment]
Hey all,

Apologies for all the issues trying to get Onboard working nicely with Svelte. We use Svelte internally at Blocknative for all of our frontends, so we'd love to improve the developer experience here.

The main issue is that bundlers like Rollup, Vite and Snowpack (which are all commonly used with Svelte) don't have good support for bundling in the node builtins, especially the `crypto` module. A lot of the wallets we support need these builtins to work correctly and that is what is causing a lot of the errors.

We are actively working on a V2 of Onboard which (among other features) will separate all of the wallets in to it's own mono repo with all of the packages so that we can isolate these dependency problems from the main library. We are also going to go through and reduce and hopefully remove the node builtin dependencies if possible or bundle the necessary deps in with the wallet modules.

In the meantime I have a [working template repo](https://github.com/blocknative/svelte-onboard-webpack) for Svelte that you can check out. It uses Webpack 4 as the bundler. It seems to be a lot more difficult to bundle the node builtins in Webpack 5 so I couldn't get that working at the moment.

**Comment by taylorjdawson** [comment]
@xpluscal @davidcallanan @zapaz Please see [comment](https://github.com/blocknative/onboard/issues/762#issuecomment-997246672) by @theurgi as they have presented a build configuration for svelte kit that is working. Sorry for all of the trouble this issue has caused!

**Comment by jakubdonovan** [comment]
Any chance to get this working with Vite?

**Comment by taylorjdawson** [comment]
@jakubdonovan can you see if the vite config in [this repo](https://github.com/blocknative/web3-onboard-react-vite-ts) works for you? It is react but should work for both

**Comment by taylorjdawson** [comment]
@jakubdonovan Specifically [here](https://github.com/blocknative/web3-onboard-react-vite-ts/blob/2e976028e3b7606ede594951e44f098c05996346/index.html#L11-L17) is important

**Comment by jakubdonovan** [comment]
> @jakubdonovan Specifically [here](https://github.com/blocknative/web3-onboard-react-vite-ts/blob/2e976028e3b7606ede594951e44f098c05996346/index.html#L11-L17) is important

So to get it to work in svelte, first install:
https://github.com/blocknative/web3-onboard

and then paste the following to the head tag in my app.html?
```
<!-- Needed for pollyfilling node builtins -->
    <script>window.global = window;</script>
    <script type="module">
      import { Buffer } from "buffer"
    
      window.Buffer = Buffer
    </script>
    <!-- Needed for pollyfilling node builtins -->
```
