### ISSUE TITLE
Add loading subscription event

### ISSUE THREAD

**Issue by nicosampler** [blocknative/onboard#668]
It would be very handy if somehow the client could receive some loading status for when Onboard is trying to establish the connection. One option could be adding a new event subscription like so `subscriptions.wallet.isConnecting`

**Comment by taylorjdawson** [comment]
> that might work when the user clicks connect button, but for example, when the user switches the network how could I show a loading until the lib has completely updated all its status?

If the user is shown the switch network modal then the `walletCheck` promise has not resolved yet. Once the user completes the network switch the `walletCheck` promise will resolve

**Comment by taylorjdawson** [comment]
@keriat @nicosampler Do you feel like this issue has been properly addressed?

**Comment by taylorjdawson** [comment]
Closing for now, please feel free to reopen if you feel that this something that needs to be addressed on our end. Thanks again for the feedback! 👍🏾
