### ISSUE TITLE
BUG: connect wallet and then dismiss

### ISSUE THREAD

**Issue by nicosampler** [blocknative/onboard#670]
There is a problem when trying to connect with a wallet and then click "dismiss" instead of "confirm", as soon as you select a wallet in the first modal, the event "wallet" is triggered with the selected wallet information, but if the user dismisses the second modal (in MM confirmation or in WC QR), there is not a "wallet" event triggered with all the values set to undefined as when you call "walletReset"

**Comment by taylorjdawson** [comment]
@nicosampler The only validation you should need is the return result from the `walletCheck` promise. If that returns `true` then you know the wallet is connected and valid to transact. What additional validation are you adding?

**Comment by taylorjdawson** [comment]
@nicosampler has your issue been addressed/resolved?

**Comment by taylorjdawson** [comment]
@nicosampler Bump and closing for now please feel free to reopen!
