### ISSUE TITLE
Metamask installation not being recognized on iOS browsers

### ISSUE THREAD

**Issue by coconutella** [blocknative/onboard#676]
The onboard dialog seems to not recognize that Metamask is installed. Is this due to iOS sandboxing? What are some UX workarounds to address this? Haven't checked on Android yet, any idea if that's also an issue?

**Comment by techgangboss** [comment]
Hey @coconutella you need to launch on Metamask's browser and it should, otherwise it will simply deeplink to Metamask. Unfortunately due to how iOS works this experience is suboptimal.
