### ISSUE TITLE
[Bug]: Omitting dappId makes binance wallet popup keep opening and closing repeatedly

### ISSUE THREAD

**Issue by StanleyDing** [blocknative/onboard#679]
### Current Behavior

Binance wallet popup keep closing and reopening itself when selecting `Binance Chain Wallet` after calling walletSelect().

### Expected Behavior

Popup should not close itself.

### Steps To Reproduce

1. Clone from [https://github.com/blocknative/react-demo](https://github.com/blocknative/react-demo)
2. Comment [dappId line](https://github.com/blocknative/react-demo/blob/master/src/services.js#L15)
3. Build and run

### Onboard Version

1.34.1

### Node Version

14.17.6

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by taylorjdawson** [comment]
@StanleyDing Thank you for reporting this issue! I've discovered the root cause and will work on getting a fix out ASAP.

**Comment by taylorjdawson** [comment]
@StanleyDing Fix incoming (see #686)

**Comment by StanleyDing** [comment]
Thanks for fix! Is there a release date?

**Comment by taylorjdawson** [comment]
@StanleyDing Working on one today! Should be this afternoon, stay tuned! 📻

**Comment by jeremyHD** [comment]
@taylorjdawson any chance to release the patch this week? :)

**Comment by taylorjdawson** [comment]
@jeremyHD yea! it is in the pipeline for today :) #705

**Comment by taylorjdawson** [comment]
@jeremyHD @StanleyDing This has been release in v1.35.0! If this issue persists please feel free to re-open 👍🏾
