### ISSUE TITLE
[Bug]: walletReset() won't reset the state completely 

### ISSUE THREAD

**Issue by roy1210** [blocknative/onboard#681]
### Current Behavior

Wallet was selected automatically in below condition even user has not selected  on UI yet.
Kindly refer to the demo video recorded from https://reactdemo.blocknative.com/

Demo:
https://www.loom.com/share/d38c4d4b3b404526a4032978eba84121

### Expected Behavior

Onboard should not automatically select the wallet in step 3.

### Steps To Reproduce

1. Choose 'Metamask' when walletSelect
2. Run 'walletReset'
3. Choose another account in Metamask UI. <- onboard will 'select' the chosen account automatically even haven't selected in the app. Also`wallet.provider` is 'undefined' in this moment, so user can't process any action.

### Onboard Version

I saw this error on 1.27.0 and 1.34.0

### Node Version

14

### What browsers are you seeing the problem on?

Chrome

**Comment by taylorjdawson** [comment]
@roy1210 Thanks for raising this issue, I'll take a look and get back to you! 👍🏾

**Comment by taylorjdawson** [comment]
@roy1210 Fix incoming on this (see #687). Great catch!

**Comment by roy1210** [comment]
@taylorjdawson 
Great!! 
Please let me know the version when the issue is fixed. Thanks!

**Comment by roy1210** [comment]
Hi @taylorjdawson 
Is v1.34.2 should be fixed the bug already?
Looks like the bug still exists in https://reactdemo.blocknative.com/

**Comment by taylorjdawson** [comment]
@roy1210 No it is in the pipeline for today though #705

**Comment by taylorjdawson** [comment]
@roy1210 Release in 1.35.0! 🎉 Please let me know if the issue persists and we can reopen 👍🏾

**Comment by jadbox** [comment]
@taylorjdawson I'm using the latest v0.7.2, and after calling resetWallet, I'm still not prompted by MM to select an account (it auto selects the last one).
