### ISSUE TITLE
[Feature]: Update Ledger Eth App

### ISSUE THREAD

**Issue by aaronbarnardsound** [blocknative/onboard#684]
### Is your request related to a problem?

Ledger [released an update](https://github.com/LedgerHQ/ledgerjs/releases/tag/v6.3.0) that supports EIP-1559 transactions.

### Feature Description

Update the Ledger Eth dependency and ensure the Ledger Onboard wallet module can successfully sign EIP-1559 transactions.

### Alternative Solutions

N/A

**Comment by taylorjdawson** [comment]
Resolved in latest release
