### ISSUE TITLE
[Bug]: Massive file size

### ISSUE THREAD

**Issue by RyRy79261** [blocknative/onboard#688]
### Current Behavior

Adding this package to an app increases the build size by 67mb

### Expected Behavior

The package to not be larger than most full scale apps

### Steps To Reproduce

Below is a test to compare fresh CRA builds before & after including `bnc-onboard`

## Before onboard

`npx create-react-app my-app --template typescript && cd my-app`

Next run `yarn build` and note the size of the output folder.

`src/App.tsx` before:
```ts
import React from 'react';
import logo from './logo.svg';
import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.tsx</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;
```

In my case: 
![image](https://user-images.githubusercontent.com/10461622/133649269-20f7a904-3b34-480c-bd05-74dfc9fd39e0.png)

## After onboard

Then add `yarn add bnc-onboard@1.32.0`

Update `src/App.tsx` to include onboard
```ts
import React from 'react';
import logo from './logo.svg';
import './App.css';

import Onboard from 'bnc-onboard';
const onboard = Onboard({
	networkId: 1
});

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.tsx</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;

```

With Onboard
![image](https://user-images.githubusercontent.com/10461622/133648617-4edd78ab-abbb-4c13-894f-d480682111f5.png)

### Onboard Version

1.32.0

### Node Version

v14.17.0

**Comment by taylorjdawson** [comment]
Hey @RyRy79261 👋🏾 What tools are you using to calculate these sizes? And are these calculations on the client side or server side? We use dynamic imports so while the build size may be large, the client side size will be substantially smaller. 
For concerns regarding the build size, most of this comes from the deps of the wallets that we support. We are working on modularizing the next iteration of onboard so that the build size will be dramatically smaller.

**Comment by taylorjdawson** [comment]
@RyRy79261 Gentle bump 🙂

**Comment by taylorjdawson** [comment]
Closing for now, please feel free to reopen if you feel there is an action item here, thanks!
