### ISSUE TITLE
[Bug]: jest version conflict create-react-app

### ISSUE THREAD

**Issue by marcoruggeri** [blocknative/onboard#690]
### Current Behavior

I'm not able to run my react app with the package bnc-onboard installed due to a jest version conflict with create-react-app

### Expected Behavior

be able to run my react app created with create-react-app with the bnc-onboard package installed

### Steps To Reproduce

1 create a react app with npx create-react-app myapp
2 yarn add bnc-onboard
3 yarn start
4 experience this issue
<img width="845" alt="Screenshot 2021-09-19 at 16 42 23" src="https://user-images.githubusercontent.com/34171105/133933769-48f7aa6c-dec9-4b4b-a744-fc2815709f1c.png">
 

### Onboard Version

1.34.2

### Node Version

14.17.3

**Comment by eliobricenov** [comment]
+1 I'm experiencing the same issue with the latest version of React.

**Comment by odd-amphora** [comment]
+1

**Comment by marcoruggeri** [comment]
I'm closing this as this has been fixed with PR #703
