### ISSUE TITLE
[Bug]: Cannot install package on Windows

### ISSUE THREAD

**Issue by davidcallanan** [blocknative/onboard#696]
### Current Behavior

When running the command `npm i bnc-onboard` on Windows, I get the following error:

![image](https://user-images.githubusercontent.com/40340425/134722694-430d714b-6a23-4051-ac58-cab97e983e16.png)

You can see details about this on my [stackoverflow question](https://stackoverflow.com/questions/69319580/npm-error-installing-onboard-js-package-on-windows).

### Expected Behavior

The command should succeed.

### Steps To Reproduce

On Windows, run `npm i bnc-onboard` inside any folder that has a valid `package.json` file.

### Onboard Version

latest

### Node Version

v16.6.2

### Relevant log output

```shell
npm ERR! code 1
npm ERR! path C:\Users\David\Documents\git\XXXXXX\node_modules\wrtc
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/download-prebuilt.js
npm ERR! 'node-pre-gyp' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\David\AppData\Local\npm-cache\_logs\2021-09-24T18_16_39_886Z-debug.log
```

**Comment by taylorjdawson** [comment]
@davidcallanan See [my comment](https://github.com/blocknative/onboard/issues/691#issuecomment-928593166) on #691

**Comment by taylorjdawson** [comment]
@davidcallanan I see this was answered on stackoverflow:
```
yarn global add node-pre-gyp
// or npm
npm install -g node-pre-gyp
```
