### ISSUE TITLE
[Bug]: Metamask fires event for different network ID relative to chain ID

### ISSUE THREAD

**Issue by kshahani** [blocknative/onboard#699]
### Current Behavior

The `chainChanged` and `networkChanged` fire different values for Avalanche.

![image](https://user-images.githubusercontent.com/22452366/134824503-fbf5ace1-f5be-4b99-b6d2-32e3dd8d1635.png)
![image](https://user-images.githubusercontent.com/22452366/134824507-0fb8b8de-8238-460a-add8-3724336dc94a.png)

### Expected Behavior

The chain ID for Avalanche should be `0xa86a`, and the network ID should be correspondingly 43114

### Steps To Reproduce

1. The user selects the Avalanche network from our app to trigger an EIP-3085 change
2. Both networkChanged and chainChanged fire, with different values, yielding a race condition.
3. The app receives events for both Ethereum and Avalanche as the new network

### Onboard Version

1.34.2

### Node Version

14

### Metamask Version

10.1.1

### What browsers are you seeing the problem on?

Chrome

**Comment by kshahani** [comment]
Perhaps this has to do with the dangling event listeners resolved in https://github.com/blocknative/onboard/pull/695?

**Comment by taylorjdawson** [comment]
@kshahani Can you test this with the latest release to see if it is fixed? #705

**Comment by kshahani** [comment]
Nice @taylorjdawson I see you made a fix! Will test it out in the next release, appreciate it 🙏

**Comment by kshahani** [comment]
@taylorjdawson Finally had an opportunity to try this out, but it looks like the issue is ongoing. Are you able to re-open this ticket for investigation again? It looks like a change has been made in the `WalletConnect` constructor, but this seems specific to the Metamask adapter.

**Comment by kshahani** [comment]
See here: 

```
Note: Ethereum has its own notion of networkID and chainID. These have no relationship to Avalanche’s view of networkID and chainID and are purely internal to the C-Chain. On Mainnet, the C-Chain uses 1 and 43114 for these values. On the Fuji Testnet, it uses 1 and 43113 for these values. networkID and chainID can also be obtained using the net_version and eth_chainId methods.
```

From https://docs.avax.network/build/avalanchego-apis/contract-chain-c-chain-api/
