### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by aaronbarnardsound** [blocknative/onboard#7]
Need to add internationalization capabilities into onboard. Devs need to have the ability to pass in an internationalization object that will get merged with our defaults and also the ability to set the language.

**Comment by dong77** [comment]
@aaronbarnardsound We are trying to integrate onboard.js into our product (Loopring.io), but we do need to have i18n support before releasing the new version. We'd like to learn where this feature is on your priority list. Thank you.

**Comment by taylorjdawson** [comment]
We're planning on doing this later down the roadmap.
