### ISSUE TITLE
[Feature]: better design options for provider-select modal

### ISSUE THREAD

**Issue by scco** [blocknative/onboard#708]
### Is your request related to a problem?

as i wanted to enhance the visual look of the provider selection modal i had a lot of barriers that simply disable me to fully "design" something visually pleasing what fits into my projects look.

- some css classes are outdated in the documentation
- most classes gets overwritten by svelte classes nobody can style as the classnames contains hashes
- some styles are hardcoded ( e.g. the blue help link )
- no way to use own provider icons ( e.g. my web3 icon library https://fusion.li )
- no way to come up with custom skeleton / div architecture to remove 2-col layout / create full-width layouts or what ever you would like to create

### Feature Description

i would love to style EVERY aspect of that component regarding the styles and have a seperation between dom-structure, styles and logic - what also means to be able to edit

- custom graphic elements like provider icons
- apply custom css classes from own design system like tailwind / an existing global css
- reorder / change what ever flexbox/grid/ structure and create loops for output multiple providers 

### Alternative Solutions

tryed to explore current applyed classes / override classes with !important with no success so i gave up and accepted the design limitations especialy for the provider list / active provider / helping text / blue link color ...

### Anything else?

writing this for this project from the gitcoin dao :  https://github.com/dcgtc/dgrants
staging : https://staging.grants.gtcdao.net

thanks for reading :)

**Comment by taylorjdawson** [comment]
@scco Thanks for this detailed feature request! For the styles have you tried using the `blocknative-custom` class as seen [here](https://docs.blocknative.com/onboard#customizing-css)?
The other issues will be addressed in future iterations of Onboard so stay tuned! 📻

**Comment by scco** [comment]
@taylorjdawson yes i tryed to use `bn-onboard-custom` but as the subclasses get overwritten by svelte stuff with on build generated hashes, i see no way to create a good result . see this examples : 

```
<ul class="bn-onboard-custom bn-onboard-modal-select-wallets svelte-q1527">
<li class="svelte-q1527"><button class="bn-onboard-custom bn-onboard-icon-button svelte-1799bj2 bn-onboard-selected-wallet"><div class="svelte-1799bj2">

```

```
ul.svelte-q1527.svelte-q1527 {
    display: flex;
    flex-flow: row wrap;
    align-items: center;
    list-style-type: none;
    margin: 1.25em 0;
    padding: 0;
    font-family: inherit;
    font-size: inherit;
    line-height: 1.15;
    box-sizing: border-box;
}
```

and some code contains hardcoded styles - see this :

`<a style="color: #4a90e2; font-size: 0.889rem; font-family: inherit;" class="bn-onboard-clickable" href="https://docs.ethhub.io/using-ethereum/wallets/intro-to-ethereum-wallets/" target="_blank" rel="noopener noreferrer">this explanation</a>
`

**Comment by taylorjdawson** [comment]
Ahh yes understood. Yes this is something we will be addressing in the near future. Thank you for submitting this request we'll be sure to incorporate it in the next iteration. 👍🏾
