### ISSUE TITLE
[Bug]: WalletConnect provider always uses chainId 1

### ISSUE THREAD

**Issue by mikheevm** [blocknative/onboard#711]
### Current Behavior

If you create onboard.js instance and pass `networkId` different than 1, the WalletConnect integration will still request mainnet network (chainId = 1)

### Expected Behavior

WalletConnect uses `networkId` passed to onboard.js configuration

### Steps To Reproduce

Try to connect Trust Wallet on https://bsc.gnosis-safe.io/, you should see the wrong network message

### Onboard Version

1.35.0

### Node Version

LTS

### Anything else?

onboard.js provider initialization: https://github.com/blocknative/onboard/blob/develop/src/modules/select/wallets/wallet-connect.ts#L54

Wc provider code: https://github.com/WalletConnect/walletconnect-monorepo/blob/v1.0/packages/providers/web3-provider/src/index.ts#L64

**Comment by taylorjdawson** [comment]
Resolved in latest release
