### ISSUE TITLE
[Feature]: Tezos support

### ISSUE THREAD

**Issue by jadbox** [blocknative/onboard#737]
### Is your request related to a problem?

We need support for Tezos chain wallet connection.

**Comment by taylorjdawson** [comment]
@jadbox Hey could you provide some more details here, thanks!

**Comment by taylorjdawson** [comment]
@jadbox gentle bump :)

**Comment by jadbox** [comment]
@taylorjdawson sorry for the lack of updates, I'm not in the Tezos ecosystem so I'm not sure what details to provide. We just have a lot of users asking for wallet login access with Tezos, which is why I'm asking here.

From: https://tezos.com/developer-portal/

There seems to be two platforms to integrate dapps to Tezos wallets:

A) "Beacon – Connecting dApps with Wallets" https://www.walletbeacon.io

B) TezBridge - TezBridge is a connector between Tezos and DApps. It works on both desktop and mobile devices. https://docs.tezbridge.com/#community

I'll ping some Tezos members to take a look at this PR to weigh in.

**Comment by taylorjdawson** [comment]
Oh okay! Unless I misunderstand, Onboard already supports Trezor.

**Comment by jadbox** [comment]
@taylorjdawson Tezos !== Trezor (Tezos is a blockchain, while Trezor is a hardware wallet). I was confused myself at first. What I'm asking here is for Tezos chain wallet support.

**Comment by taylorjdawson** [comment]
@jadbox Haha wow sorry about that! Okay so I believe that it should work as is as long as the wallet you are using supports Tezos, are you experiencing any specific issues?

**Comment by taylorjdawson** [comment]
@jadbox Checking in on this 🙂

**Comment by taylorjdawson** [comment]
@jadbox Chain support is wallet dependent but if you want you may open a PR to support the network name for Tezos. See example here for [Fantom network support](https://github.com/blocknative/onboard/pull/746/files)

Closing for now please feel free to re-open if need be.
