### ISSUE TITLE
[Bug]: Detected Wallet appears as a wallet option in the wallet select step.

### ISSUE THREAD

**Issue by lamaro** [blocknative/onboard#740]
### Current Behavior

I'm adding only metamask
wallets: [
        {
          walletName: "metamask",
        }]

But a "Detected wallet" appears in the list of wallets.

When clicked: 
We have detected that you already have MetaMask installed. If you would prefer to use Detected Wallet instead, then click below to install.
Tip: If you already have Detected Wallet installed, check your browser extension settings to make sure that you have it enabled and that you have disabled any other browser extension wallets. Then refresh the page.

with two buttons, Back and Open Detected Wallet (nothing happens when clicked)

I've google Detected Wallet but nothing appears..

### Expected Behavior

Just the metamask wallet selector

### Steps To Reproduce

Rinkeby network, localhost.

### Onboard Version

^1.35.4

### Node Version

14.17.0

### What browsers are you seeing the problem on?

Chrome

**Comment by lamaro** [comment]
adding **preferred: true** to the only wallets in the array, removes the Detected Wallet

**Comment by lamaro** [comment]
Just noticed that the Detected Wallet appears when Show More is clicked. 
how to remove the Detected Wallet option?

**Comment by lamaro** [comment]
Reviewing the docs, found: 

The detected wallet will be displayed as an option when an injected Ethereum provider is detected, but it is not recognized by Onboard. This allows users to connect to your app with any provider that conforms to the EIP-1193 standard.

Is there any way to prevent showing it? disable it, or check which is the provider that is making it to appear?

**Comment by NicolasJEngler** [comment]
@lamaro, it looks like it could be related to the latest MetaMask version? As soon as I disable MetaMask's extension, the "Detected Wallet" goes away, and given that Onboard looks for injected Ethereum providers, and MetaMask injects one, could be related.

Since it seems that the detected wallet is always the first option in the list, one way of disabling it could be via CSS, setting `display: none` to that `:first-child` in particular.

**Comment by taylorjdawson** [comment]
@lamaro You can use this to disable if need be 👍🏾 
![image](https://user-images.githubusercontent.com/29665732/141308540-66b6e2eb-43a6-486c-8eec-58db2e91a4b5.png)

https://docs.blocknative.com/onboard#initialization-1

**Comment by lamaro** [comment]
Unfortunately, this solution didn't worked for me. The Detected wallet still appearing =(

This is my configuration

`walletSelect: {
      heading: "Connect your Wallet",
      description: "Onboard JS Boilerplate",
      explanation: "",
      wallets: [
        {
          walletName: "detectedwallet",
          display: {
            desktop: false,
            mobile: false,
          },
        },
        {
          walletName: "metamask",
        },
      ],
    },
    walletCheck: [
      { checkName: "derivationPath" },
      { checkName: "connect" },
      { checkName: "accounts" },
      { checkName: "network" },
      { checkName: "balance", minimumBalance: "100000" },
    ],`

It seems that Detected Wallet skips the mobile/desktop display prop.

any Clue?

**Comment by taylorjdawson** [comment]
@lamaro I will need to debug this locally and get back to you 👍

**Comment by taylorjdawson** [comment]
@lamaro  fixed in latest release! v1.35.5
