### ISSUE TITLE
[Bug]: Balance Fetch Returning Null in the first Attempt 

### ISSUE THREAD

**Issue by Huzaifa-Asif** [blocknative/onboard#741]
### Current Behavior

Language: React.js (17.0.2)
Network: 3 (Ropsten)

I have encountered an issue in this library while fetching account balance.

After Successful walletSelect() and walletCheck() method execution I call wallet getState() but it returns the balance as null but I have 0.3 ether in my wallet and on the second try when I again click on wallet connect and select metamask then in return it provides correct balance.  

Kindly let me know what I am doing wrong in the code so that I can resolve this issue, I am pasting my code below for reference.

**Library Import and Onboard Initialization Code** 

```
import Onboard from 'bnc-onboard'
import Web3 from 'web3'

let web3
const onboard = Onboard({
    dappId: 'Api key',  // [String] The API key of Blocknative
    networkId: 3,  // [Integer] The Ethereum network ID your Dapp uses.
    subscriptions: {
      wallet: wallet => {
         web3 = new Web3(wallet.provider)
      }
    }
});
```

**Connect Wallet Code** 

```
async function ConnectWallet() {
  const walletSelected = await onboard.walletSelect();
  if(walletSelected){
    const readyToTransact = await onboard.walletCheck();
    if(readyToTransact){
      const currentState = await onboard.getState()
      console.log(currentState)
    }
  }
}
```

### Expected Behavior

I should get the actual balance in balance attribute instead of null in the first attempt, right now I have to connect wallet twice to get balance value.

### Onboard Version

1.35.4

### Node Version

12.18.0

**Comment by taylorjdawson** [comment]
@Huzaifa-Asif 
What happens when you subscribe to the balance update rather than polling for the balance via getState? 
```typescript
const onboard = Onboard({
    dappId: 'Api key',  // [String] The API key of Blocknative
    networkId: 3,  // [Integer] The Ethereum network ID your Dapp uses.
    subscriptions: {
      balance: (value) => {console.log('balance', value)},
      wallet: wallet => {
         web3 = new Web3(wallet.provider)
      }
    }
});
```

**Comment by taylorjdawson** [comment]
@Huzaifa-Asif gentle bump :)

**Comment by taylorjdawson** [comment]
@Huzaifa-Asif Closing for now but please feel free to re-open if issue persists 👍🏾
