### ISSUE TITLE
[Bug]: Maximum call stack size exceeded error

### ISSUE THREAD

**Issue by jahvi** [blocknative/onboard#742]
### Current Behavior

This might be an issue with Vuex or Nuxt but I thought I'll post here in case someone has experienced it before.

I'm trying to use Vuex and Onboard.js to store a web3 provider in my DApp, however I keep getting a `Maximum call stack size exceeded` when I try to commit the selected wallet in my state, here's how my files look like:

**store/ethers.js**

```js
import { ethers } from 'ethers';
import Onboard from 'bnc-onboard';

export const state = () => ({
  address: '',
  onboard: null,
  wallet: null,
});

export const actions = {
  async initOnboard({ commit, state }) {
    const onboard = Onboard({
      networkId: 4,
      walletSelect: {
        wallets: [
          { walletName: 'metamask' },
        ],
      },
      subscriptions: {
        wallet: (wallet) => {
          // If I comment out this line it works...
          commit('SET_WALLET', wallet);

          localStorage.setItem('wallet', wallet.name);
        },
        address: (address) => {
          commit('SET_ADDRESS', address);
        },
      },
    });

    if (localStorage.getItem('wallet')) {
      await onboard.walletSelect(localStorage.getItem('wallet'));
    }

    commit('SET_ONBOARD', onboard);
  },
};

export const mutations = {
  SET_WALLET(state, wallet) {
    state.wallet = wallet;
  },
  SET_ONBOARD(state, onboard) {
    state.onboard = onboard;
  },
  SET_ADDRESS(state, address) {
    state.address = address;
  },
};
```

**index.vue**
```html
<template>
  <button @click="connect">
    Connect
  </button>
</template>

<script>
import { mapActions } from 'vuex';

export default {
  mounted() {
    this.$store.dispatch('ethers/initOnboard');
  },
  methods: {
    ...mapActions('ethers', ['connect']),
  },
};
</script>
```

I don't think it's a problem with the `ethers` library as I swapped it for `web3` and got the same issue. If I comment out the `commit('SET_WALLET', wallet);` line the error is gone but I need a way to access this in my app.

I think I'm doing something wrong with the `commits` in my store and it's causing some recursion but I haven't been able to figure out what it is.

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/xzOjF.jpg

### Expected Behavior

Wallet should be able to be saved in Vuex state without causing call stack errors.

### Steps To Reproduce

Here's a link with a reproduction of the issue, you'll need metamask installed. If you click the "connect" button and select "metamask" you'll see the error in the console.

Preview: https://f6875.sse.codesandbox.io/

Editor: https://codesandbox.io/s/upbeat-ardinghelli-f6875?file=/pages/index.vue

### Onboard Version

1.35.4

### Node Version

14.17.4

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by taylorjdawson** [comment]
@jahvi Sorry for the delayed response! Were you able to get this working?

**Comment by jahvi** [comment]
@taylorjdawson Yes although I'm not sure why it works, I had to freeze the onboard object before committing to vuex, if you have any idea why I works I'd love to know 😄

```js
commit('SET_WALLET', Object.freeze(wallet));
```

**Comment by simonzg** [comment]
I still see this issue with @web3-onboard/core@2.21.0. tried @jahvi 's method but had no luck. Any suggestions?

**Comment by simonzg** [comment]
I solved my problem by disabling the strict mode of Vuex. It seems like something underneath is trying to modify the states outside of the mutations, but I was not able to locate the code that does this.

Hope this helps.
