### ISSUE TITLE
[Feature]: Solana wallets support: Phantom, Solflare

### ISSUE THREAD

**Issue by sidlovskyy** [blocknative/onboard#752]
### Is your request related to a problem?

Could you please let me know:

- Are there any plans to integrate Solana wallets.
- Is that technically possible with [Custom Modules](https://docs.blocknative.com/onboard#creating-custom-modules) or there are some restrictions that could prevent it (as Solana is non EVM compatible).

**Comment by taylorjdawson** [comment]
@sidlovskyy You can use the custom modules to integrate Solana wallets the only thing you won't get are the API specific features of Onboard as we don't support it on our backend as of yet.

**Comment by taylorjdawson** [comment]
@sidlovskyy Does that resolve this issue for you?

**Comment by taylorjdawson** [comment]
@sidlovskyy This can be done via custom modules or through a PR. Here is an example of a [wallet integration PR](https://github.com/blocknative/onboard/pull/757/files). Closing for now please feel free to reopen if need be 👍🏾
