### ISSUE TITLE
[Bug]: Detected wallet option no longer appears in select modal

### ISSUE THREAD

**Issue by jfschwarz** [blocknative/onboard#765]
### Current Behavior

We use a custom Chrome extension that injects an EIP-1193 provider in `window.ethereum`. Up until recently, it was showing up as "Detected" option in the select modal when browsing Dapps using onboard (like curve.fi). This stopped working with version `1.35.5`, I believe.

If I understand https://github.com/blocknative/onboard/pull/743 correctly, the `detectedwallet` option must now be explicitly enabled to show up. This might be deliberate, but it's still a breaking change.

### Expected Behavior

A generic injected providers should continue showing up as "Detected" option in the select modal as there are users who came to rely on this.

The "Detected" option should not show up if the injected provider is identified as one of the known ones like MetaMask, effectively fixing the bug https://github.com/blocknative/onboard/issues/740 without introducing a breaking change.

### Onboard Version

^1.35.5

### Node Version

14.17.0

### What browsers are you seeing the problem on?

Chrome

**Comment by taylorjdawson** [comment]
@jfschwarz Are you saying that now your injected provider is not showing up on the list of wallets at "Detected"? Which wallet is this? And is it a known wallet?

**Comment by taylorjdawson** [comment]
@jfschwarz Also can you provide repro steps? Thanks!

**Comment by jfschwarz** [comment]
Thank you, @taylorjdawson! What I'm saying is that generic EIP-1193 wallets (like ours) no longer show up in apps using onboard.js **without the `detectedwallet` option enabled**. I understand that this change was introduced with a bugfix in `v1.35.5`, however there are apps that came to rely on the "bug" that detected wallets generally appear in the list.

**Comment by jfschwarz** [comment]
Having `detectedwallet` enabled seems like a good default, so maybe at least consider adding this option to the example snippet in your docs (https://docs.blocknative.com/onboard#initialize-onboard).

**Comment by taylorjdawson** [comment]
@jfschwarz I don't think this issue is related to that PR that you referenced. The PR that referenced fixed an issue where a builtin wallet was also showing up as detected. If your wallet isn't builtin to Onboard then it will show up as detected. Which wallet are you using so I can test/debug

**Comment by jfschwarz** [comment]
Thank you, @taylorjdawson! We're using this wallet: https://github.com/gnosis/zodiac-pilot

This is the provider we inject as `window.ethereum`: https://github.com/gnosis/zodiac-pilot/blob/main/src/bridge/iframe.ts

This line is our current workaround for making it possible to use the wallet with curve.fi: https://github.com/gnosis/zodiac-pilot/blob/main/src/bridge/iframe.ts#L100
(curve.fi uses onboard.js without the `detectedwallet` option enabled. To make it possible to connect to it from the onboard modal, our wallet pretends to be Blank Wallet.)

**Comment by taylorjdawson** [comment]
@jfschwarz Detected wallets show up by default as of version [v1.31.0](https://github.com/blocknative/onboard/releases/tag/1.31.0) of Onboard it is no longer an opt-in. 

See [this issue](https://github.com/blocknative/onboard/issues/600) for more details and specifically this comment: https://github.com/blocknative/onboard/issues/600#issuecomment-927357953

We will check with curve to see what version they are using.

In the meantime could you try using the [react-demo](https://reactdemo.blocknative.com/) and see if your wallet shows up without `isBlankWallet`?

**Comment by jfschwarz** [comment]
Thank you for sending the the react-demo link, @taylorjdawson. The demo app suffers under the very same issue as curve.fi.

The detected wallet option does not show up.

![image](https://user-images.githubusercontent.com/524089/155685783-56b3538f-495f-464c-8d42-7c096daa681a.png)

I can use a similar hack to make it work (adding `isTally: true` to the injected provider object).

**Comment by taylorjdawson** [comment]
@jfschwarz Awesome thanks for this info, I am going to try and repro with the Zodiac wallet. I assume I can just pull and build and run?

**Comment by jfschwarz** [comment]
Thank you so much for looking into this. Here are the repro steps:

- Connect to any wallet via WalletConnet
  - You can use this Rinkeby Safe for example: https://gnosis-safe.io/app/rin:0xDA5A5816c54C436c69535Ca3172826de61546f6e/apps?appUrl=https://apps.gnosis-safe.io/wallet-connect
- For "DAO Safe" enter: `0x87eb5F76C3785936406fa93654F39b2087FD8068`
- For "Zodiac Modifier or Module Address" select: `0x3f9b49c750DDcD292370d3FCe6Fa139CdeD4698c`
- For "Dapp Url" enter: `https://reactdemo.blocknative.com/`
- Click "Launch" button

**Comment by jfschwarz** [comment]
> I will say though that this could be solved by just adding Zodiac into onboard as a wallet module via PR. This would require curve (and others) to update their version of onboard to show the new wallet. However, fixing the wallet detection logic would also require them to update onboard. In that case it may be best to integrate Zodiac directly such that it shows up in the wallet selection modal.

We definitely plan to add Zodiac Pilot into onboard before when publicly releasing it. However, it seems like we would not only require app providers to upgrade their onboard dependencies (which should be a routine/automated thing) but they would also have to manually update their onboard wallet configurations. Therefore, we'd still like to have it show up as a generic detected wallet.

**Comment by taylorjdawson** [comment]
Awesome thanks for those steps, do you know the issue here? 
<img width="544" alt="image" src="https://user-images.githubusercontent.com/29665732/155758584-e66d1890-9927-4e92-a03c-20e2733feccb.png">

Btw

**Comment by jfschwarz** [comment]
Ah, right... I assume you walletconnected to your own wallet? I just realized you actually have to use the one I posted above for it to work:

https://gnosis-safe.io/app/rin:0xDA5A5816c54C436c69535Ca3172826de61546f6e/apps?appUrl=https://apps.gnosis-safe.io/wallet-connect

**Comment by taylorjdawson** [comment]
@jfschwarz Great it is now working, I'll let you know once I discover the issue!

**Comment by taylorjdawson** [comment]
@jfschwarz Got it figured out! You can track it [here](https://github.com/blocknative/onboard/pull/841).

**Comment by jfschwarz** [comment]
Amazing! Thank you so much, @taylorjdawson
