### ISSUE TITLE
[Bug]: Network Name not changing when prompted to switch network after updating the onboard config

### ISSUE THREAD

**Issue by kelokchan** [blocknative/onboard#768]
### Current Behavior

I'm trying to allow the user to switch network from `mumbai` to `rinkeby` but I'm getting incorrect message when the modal is displayed. Initially I have the onboard object initialized using this code

```
import Onboard from 'bnc-onboard';

onboard = Onboard({
  ...
   networkId: 80001,
   networkName: 'mumbai',
  ...
})
```

Then I try to switch the network to rinkeby using this
```
onboard.config({ networkId: 4 })
```

However, when the switch network modal is shown, the target network in the message is still `mumbai`
```
We've detected that you need to switch your wallet's network from unknown to mumbai.
``` 

I couldn't re-initialize the onboard object either as I'm getting other errors.   

### Expected Behavior

Expected the switch network prompt to display correct target network after updating the `networkId` config

### Steps To Reproduce

1. Initialize onboard using `mumbai` as `networkName` and `80001` as `networkId`
2. Update onboard `networkId` in `config`to `4` 
3. Call `walletCheck`

### Onboard Version

1.37.0

### Node Version

v16.11.1

### What browsers are you seeing the problem on?

Chrome

**Comment by taylorjdawson** [comment]
@kelokchan What errors do you get when you try to re-initialize the onboard object? I would do this for now as we look further into the issue. In [Mempool Explorer](https://explorer.blocknative.com/?v=1.29.9&0=ethereum&1=main) we always re-initialize whenever making configuration changes.

**Comment by taylorjdawson** [comment]
@kelokchan re-initializing onboard is best as just changing the `networkName` & `networkId` with the `config` method will cause problems with hardware wallets. This has been fixed/address in in [Onboard v2](https://github.com/blocknative/onboard/tree/feature/v2#readme)

**Comment by taylorjdawson** [comment]
@kelokchan Could you open a new issue with the errors you are getting once you re-initialize? Thanks!
