### ISSUE TITLE
[Bug]: Remote build error on Heroku

### ISSUE THREAD

**Issue by iampick** [blocknative/onboard#774]
### Current Behavior

remote: -----> Installing dependencies
remote:        Installing node modules
remote:        npm ERR! Error while executing:
remote:        npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/blocknative/onboard.git
remote:        npm ERR! 
remote:        npm ERR! Host key verification failed.
remote:        npm ERR! fatal: Could not read from remote repository.
remote:        npm ERR! 
remote:        npm ERR! Please make sure you have the correct access rights
remote:        npm ERR! and the repository exists.
remote:        npm ERR! 
remote:        npm ERR! exited with error code: 128

### Onboard Version

^1.35.2

### Node Version

14.18.2

**Comment by taylorjdawson** [comment]
@iampick I will need more context to fully address this issue. Could you possible provide your repo and/or package.json file so I can further assist? Thanks!

**Comment by taylorjdawson** [comment]
@iampick ping :)

**Comment by taylorjdawson** [comment]
@iampick Closing for now please feel free to re-open if issue persists.

**Comment by iampick** [comment]
Hi, 
Sorry for the late update. I've switched from NPM to Yarn. it's working fine.

thanks
