### ISSUE TITLE
[Bug]: Connecting trough walletConnect starts polling indefinitely

### ISSUE THREAD

**Issue by nicosampler** [blocknative/onboard#780]
### Current Behavior

I'm having a problem when I select WalletConnect, it starts to call two RPC methods [`eth_getBalance, eth_blockNumber`] and never stops. Perhaps it is a problem with my own code, but I've been debugging it for two days and I can not find the problem.

This is what I see on Infura:
![image](https://user-images.githubusercontent.com/4376509/149566998-b71ba8be-8f7a-47cb-9062-8a9ada10fca9.png)

This is a video where you can see that after selecting WalletConnect in the wallet selection modal, it starts fetching from the RPC:
https://www.loom.com/share/efb2ebb6fa004a099b094e8858ccd523

This is a video where I can connect to MM without problems:
https://www.loom.com/share/a88473eb5a054cf49c7d8614615a6b4b

### Expected Behavior

It should stop fetching the RPC.

### Onboard Version

1.35.x &  1.37.0

### Node Version

14.17.5

**Comment by taylorjdawson** [comment]
@nicosampler Are you providing a blocknative API key in your implementation?

**Comment by taylorjdawson** [comment]
@nicosampler ping :)

**Comment by taylorjdawson** [comment]
@nicosampler closing for now please feel free to re-open if issue persists.
