### ISSUE TITLE
[Feature]: Keep user session

### ISSUE THREAD

**Issue by AndonMitev** [blocknative/onboard#783]
### Is your request related to a problem?

Currently if i reload my app users needs to connect again cuz there is no stored session, is it possible to save the address in localstorage and somehow provide it from there to the package to keep the user session and they do not have to login again

**Comment by DisruptiveMind** [comment]
hey @AndonMitev, just chiming in here, the demo has an example:

https://github.com/blocknative/react-demo/blob/e7e0386ce821234d59027a185765208ba2634d7f/src/App.js#L67

**Comment by Adamj1232** [comment]
@AndonMitev - Closing issue as @DisruptiveMind noted there is an example of this in the React Demo project that can be seen here
https://github.com/blocknative/react-demo/blob/e7e0386ce821234d59027a185765208ba2634d7f/src/App.js#L67
&
https://github.com/blocknative/react-demo/blob/e7e0386ce821234d59027a185765208ba2634d7f/src/App.js#L82
