### ISSUE TITLE
[Bug]: `accountSelect` in `account.ts` not rendering `select account` modal properly

### ISSUE THREAD

**Issue by greedythib** [blocknative/onboard#784]
### Current Behavior

Hello, 

I am currently facing this display bug when trying to connect my ledger wallet:

![Capture d’écran 2022-01-18 à 6 05 56 PM](https://user-images.githubusercontent.com/12110896/149987682-fe5ee741-f54f-408a-ac69-ea8a5d9446d6.png)

Any idea how I could fix this? 

Thanks

### Onboard Version

1.36.0 (using @chainsafe/web3-context)

### Node Version

16

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by Adamj1232** [comment]
@greedythib there will be a fix for this in the next release. 
Thank you for reporting this issue and keep an eye out for the new Onboard v2 coming out soon!
