### ISSUE TITLE
[Bug]: Torus Transaction Error - gasPrice but also included maxFeePerGas, these cannot be mixed

### ISSUE THREAD

**Issue by jadbox** [blocknative/onboard#799]
### Current Behavior

When using the latest version of Onboard `1.37.1`, using Torus, and connecting to Polygon chain 137 and try to perform a transaction, I get the below error:
```
Uncaught (in promise) Error: Invalid transaction params: specified gasPrice but also included maxFeePerGas, these cannot be mixed
    at getEthJsonRpcError (chunk-vendors.d7195693.js:64:300066)
```

I've also filed a bug with Torus if the issue is on their side: https://github.com/torusresearch/torus-embed/issues/410

### Expected Behavior

no error should occur

### Steps To Reproduce

1. Select Torus from Onboard wallet selection and use a Polygon chain (137)
2. Perform any transaction that requires gas
3. see browser console log for error

### Onboard Version

1.37.1

### Node Version

v14.18.3

### What browsers are you seeing the problem on?

Chrome

**Comment by taylorjdawson** [comment]
@jadbox Is it safe to say that this is a torus issue and can be closed?

**Comment by jadbox** [comment]
I believe so. Closing
