### ISSUE TITLE
[Feature]: Make networkId parameter optional

### ISSUE THREAD

**Issue by morozj01** [blocknative/onboard#800]
### Is your request related to a problem?

We would like to migrate to Onboard but our application is multi-chain and generally defaults to using the chain that the user's wallet is already connected to.  Tying the application to a single networkId and requesting that the user switches chains upon connecting their wallet may lead to a poor UX by requiring an unnecessary extra step. 

### Feature Description

Allow the networkId parameter to be optional when instantiating onboard and do not make a switch chain RPC call when networkId is omitted. 

Apologies if this is already possible and thanks in advance!

**Comment by imsys** [comment]
+1 I also would like this feature. I was thinking in proposing it, but you have done it first. :)

**Comment by taylorjdawson** [comment]
@morozj01 @imsys In [Onboard v2](https://github.com/blocknative/onboard/blob/feature/v2/packages/core/README.md) you provide an array of networks that your dapp supports. I believe that would address the issue you are experiencing? If so, we suggest waiting for the O2 release as this feature will be there by default.

Below is an example from the README:

```js
import Onboard from '@bn-onboard/core'
import injectedModule from '@bn-onboard/injected-wallets'

const ETH_MAINNET_RPC = `https://mainnet.infura.io/v3/${INFURA_KEY}`
const ETH_RINKEBY_RPC = `https://rinkeby.infura.io/v3/${INFURA_KEY}`
const MATIC_MAINNET_RPC = 'https://matic-mainnet.chainstacklabs.com'

const injected = injectedModule()

const onboard = Onboard({
  wallets: [injected],
  chains: [
    {
      id: '0x1',
      token: 'ETH',
      label: 'Ethereum Mainnet',
      rpcUrl: ETH_MAINNET_RPC
    },
    {
      id: '0x4',
      token: 'rETH',
      label: 'Ethereum Rinkeby Testnet',
      rpcUrl: ETH_RINKEBY_RPC
    },
    {
      id: '0x89',
      token: 'MATIC',
      label: 'Matic Mainnet',
      rpcUrl: MATIC_MAINNET_RPC
    }
  ],
  appMetadata: {
    name: 'Token Swap',
    icon: myIcon, // svg string icon
    description: 'Swap tokens for other tokens',
    recommendedInjectedWallets: [
      { name: 'MetaMask', url: 'https://metamask.io' },
      { name: 'Coinbase', url: 'https://wallet.coinbase.com/' }
    ]
  }
  i18n: {
    en: {
      connect: {
        selectingWallet: {
          header: 'custom text header'
        }
      }
    }
  }
})
```

**Comment by honestbonsai** [comment]
@morozj01 I was looking for something similar. I put in the required networkId as 1 (Ethereum), though our application also supports 137 (Polygon).

I would prefer to listen to the user's wallet's network and display "Invalid Network" if they are connected to an unsupported network. For v1 Onboard, I just did the following to bypass the network check:

```
const onboard = Onboard({
  ...
  networkId: 1,
  walletCheck: [{checkName: "connect"}]
})
```
