### ISSUE TITLE
[Feature]: Add Magic wallet module

### ISSUE THREAD

**Issue by jacobkaufmann** [blocknative/onboard#806]
### Is your request related to a problem?

No.

### Feature Description

Add a built-in wallet module for the [Magic](https://magic.link) wallet.

### Alternative Solutions

The alternative is to implement a custom wallet module for Magic, but Onboard already supports [Fortmatic](https://fortmatic.com), which is now Magic. It seems that a custom wallet module implementation would duplicate the work already done to support Fortmatic.

**Comment by taylorjdawson** [comment]
@jacobkaufmann Thanks for the feature request! Would you be able to [submit a PR](https://github.com/blocknative/onboard/pull/805) to add the wallet? Otherwise we'll probably wait and integrate it into [Onboard V2](https://github.com/blocknative/onboard/tree/feature/v2)
